import type { DashboardLocale } from "@/lib/dashboardI18n";
import { cryptoMarketCopyFor } from "@/lib/cryptoMarketI18n";

type ClassicMarketExtra = {
  navLabel: string; live: string; connecting: string; waiting: string; favorites: string; coreAssets: string;
  searchResults: string; activeSearch: string; clearSearch: string; expandHint: string; starsCalculator: string;
  starsCount: string; calculationCurrency: string; referenceEstimate: string; loadingMarket: string; recoveringMarket: string;
  currentPrice: string; bestBuy: string; bestSell: string; dayRange: string; livePriceChart: string; realMarketData: string;
  chartSync: string; addFavorite: string; removeFavorite: string;
};

const extra: Record<DashboardLocale, ClassicMarketExtra> = {
  fa: { navLabel: "بازار ارز", live: "اتصال لحظه‌ای", connecting: "در حال اتصال", waiting: "در انتظار اتصال", favorites: "علاقه‌مندی‌ها", coreAssets: "ارزهای اصلی", searchResults: "نتایج جست‌وجو", activeSearch: "جست‌وجو بین بازارهای فعال", clearSearch: "پاک‌کردن جست‌وجو", expandHint: "روی هر ارز بزنید تا جزئیات زیر همان کارت باز شود.", starsCalculator: "ماشین‌حساب Telegram Stars", starsCount: "تعداد Stars", calculationCurrency: "واحد محاسبه", referenceEstimate: "برآورد مرجع", loadingMarket: "در حال دریافت داده‌های بازار…", recoveringMarket: "دادهٔ بازار موقتاً در حال بازیابی است.", currentPrice: "قیمت فعلی", bestBuy: "بهترین خرید", bestSell: "بهترین فروش", dayRange: "دامنهٔ ۲۴ ساعت", livePriceChart: "قیمت و نمودار زنده", realMarketData: "داده‌های واقعی بازار", chartSync: "در حال همگام‌سازی نمودار…", addFavorite: "افزودن به علاقه‌مندی‌ها", removeFavorite: "حذف از علاقه‌مندی‌ها" },
  en: { navLabel: "Currency market", live: "Live connection", connecting: "Connecting", waiting: "Waiting for connection", favorites: "Favorites", coreAssets: "Core assets", searchResults: "Search results", activeSearch: "Searching active markets", clearSearch: "Clear search", expandHint: "Select a market to expand its detail directly below.", starsCalculator: "Telegram Stars calculator", starsCount: "Number of Stars", calculationCurrency: "Calculation currency", referenceEstimate: "Reference estimate", loadingMarket: "Loading market data…", recoveringMarket: "This market is recovering.", currentPrice: "Current price", bestBuy: "Best buy", bestSell: "Best sell", dayRange: "24-hour range", livePriceChart: "Live price and chart", realMarketData: "Real market data", chartSync: "Syncing chart…", addFavorite: "Add to favorites", removeFavorite: "Remove from favorites" },
  ar: { navLabel: "سوق العملات", live: "اتصال مباشر", connecting: "جارٍ الاتصال", waiting: "بانتظار الاتصال", favorites: "المفضلة", coreAssets: "العملات الأساسية", searchResults: "نتائج البحث", activeSearch: "البحث في الأسواق النشطة", clearSearch: "مسح البحث", expandHint: "اختر عملة لعرض التفاصيل تحت بطاقتها مباشرة.", starsCalculator: "حاسبة Telegram Stars", starsCount: "عدد Stars", calculationCurrency: "عملة الحساب", referenceEstimate: "تقدير مرجعي", loadingMarket: "جارٍ تحميل بيانات السوق…", recoveringMarket: "بيانات السوق قيد الاستعادة مؤقتاً.", currentPrice: "السعر الحالي", bestBuy: "أفضل شراء", bestSell: "أفضل بيع", dayRange: "نطاق 24 ساعة", livePriceChart: "سعر ورسم بياني مباشر", realMarketData: "بيانات السوق الفعلية", chartSync: "جارٍ مزامنة الرسم…", addFavorite: "إضافة إلى المفضلة", removeFavorite: "إزالة من المفضلة" },
  tr: { navLabel: "Döviz piyasası", live: "Canlı bağlantı", connecting: "Bağlanıyor", waiting: "Bağlantı bekleniyor", favorites: "Favoriler", coreAssets: "Temel varlıklar", searchResults: "Arama sonuçları", activeSearch: "Etkin piyasalarda aranıyor", clearSearch: "Aramayı temizle", expandHint: "Ayrıntıları kartın hemen altında açmak için bir piyasa seçin.", starsCalculator: "Telegram Stars hesaplayıcı", starsCount: "Stars sayısı", calculationCurrency: "Hesaplama para birimi", referenceEstimate: "Referans tahmini", loadingMarket: "Piyasa verileri yükleniyor…", recoveringMarket: "Piyasa verileri geçici olarak kurtarılıyor.", currentPrice: "Güncel fiyat", bestBuy: "En iyi alış", bestSell: "En iyi satış", dayRange: "24 saatlik aralık", livePriceChart: "Canlı fiyat ve grafik", realMarketData: "Gerçek piyasa verileri", chartSync: "Grafik eşitleniyor…", addFavorite: "Favorilere ekle", removeFavorite: "Favorilerden kaldır" },
  ru: { navLabel: "Валютный рынок", live: "Подключение в реальном времени", connecting: "Подключение", waiting: "Ожидание подключения", favorites: "Избранное", coreAssets: "Основные активы", searchResults: "Результаты поиска", activeSearch: "Поиск по активным рынкам", clearSearch: "Очистить поиск", expandHint: "Выберите рынок, чтобы раскрыть детали прямо под его карточкой.", starsCalculator: "Калькулятор Telegram Stars", starsCount: "Количество Stars", calculationCurrency: "Валюта расчёта", referenceEstimate: "Справочная оценка", loadingMarket: "Загрузка рыночных данных…", recoveringMarket: "Рыночные данные временно восстанавливаются.", currentPrice: "Текущая цена", bestBuy: "Лучшая покупка", bestSell: "Лучшая продажа", dayRange: "Диапазон за 24 часа", livePriceChart: "Цена и график в реальном времени", realMarketData: "Реальные рыночные данные", chartSync: "Синхронизация графика…", addFavorite: "Добавить в избранное", removeFavorite: "Удалить из избранного" },
  es: { navLabel: "Mercado de divisas", live: "Conexión en vivo", connecting: "Conectando", waiting: "Esperando conexión", favorites: "Favoritos", coreAssets: "Activos principales", searchResults: "Resultados de búsqueda", activeSearch: "Buscando mercados activos", clearSearch: "Borrar búsqueda", expandHint: "Seleccione un mercado para desplegar los detalles justo debajo de su tarjeta.", starsCalculator: "Calculadora de Telegram Stars", starsCount: "Cantidad de Stars", calculationCurrency: "Moneda de cálculo", referenceEstimate: "Estimación de referencia", loadingMarket: "Cargando datos de mercado…", recoveringMarket: "Los datos del mercado se están recuperando temporalmente.", currentPrice: "Precio actual", bestBuy: "Mejor compra", bestSell: "Mejor venta", dayRange: "Rango de 24 horas", livePriceChart: "Precio y gráfico en vivo", realMarketData: "Datos reales del mercado", chartSync: "Sincronizando gráfico…", addFavorite: "Añadir a favoritos", removeFavorite: "Quitar de favoritos" },
  fr: { navLabel: "Marché des devises", live: "Connexion en direct", connecting: "Connexion en cours", waiting: "En attente de connexion", favorites: "Favoris", coreAssets: "Actifs principaux", searchResults: "Résultats de recherche", activeSearch: "Recherche sur les marchés actifs", clearSearch: "Effacer la recherche", expandHint: "Sélectionnez un marché pour afficher le détail sous sa carte.", starsCalculator: "Calculatrice Telegram Stars", starsCount: "Nombre de Stars", calculationCurrency: "Devise de calcul", referenceEstimate: "Estimation de référence", loadingMarket: "Chargement des données de marché…", recoveringMarket: "Les données du marché se rétablissent temporairement.", currentPrice: "Prix actuel", bestBuy: "Meilleur achat", bestSell: "Meilleure vente", dayRange: "Fourchette sur 24 heures", livePriceChart: "Prix et graphique en direct", realMarketData: "Données réelles du marché", chartSync: "Synchronisation du graphique…", addFavorite: "Ajouter aux favoris", removeFavorite: "Retirer des favoris" },
  pt: { navLabel: "Mercado de moedas", live: "Conexão ao vivo", connecting: "Conectando", waiting: "Aguardando conexão", favorites: "Favoritos", coreAssets: "Ativos principais", searchResults: "Resultados da busca", activeSearch: "Buscando mercados ativos", clearSearch: "Limpar busca", expandHint: "Selecione um mercado para abrir os detalhes logo abaixo do cartão.", starsCalculator: "Calculadora Telegram Stars", starsCount: "Quantidade de Stars", calculationCurrency: "Moeda do cálculo", referenceEstimate: "Estimativa de referência", loadingMarket: "Carregando dados do mercado…", recoveringMarket: "Os dados do mercado estão sendo recuperados temporariamente.", currentPrice: "Preço atual", bestBuy: "Melhor compra", bestSell: "Melhor venda", dayRange: "Faixa de 24 horas", livePriceChart: "Preço e gráfico ao vivo", realMarketData: "Dados reais do mercado", chartSync: "Sincronizando gráfico…", addFavorite: "Adicionar aos favoritos", removeFavorite: "Remover dos favoritos" },
  it: { navLabel: "Mercato valutario", live: "Connessione in tempo reale", connecting: "Connessione", waiting: "In attesa di connessione", favorites: "Preferiti", coreAssets: "Asset principali", searchResults: "Risultati della ricerca", activeSearch: "Ricerca nei mercati attivi", clearSearch: "Cancella ricerca", expandHint: "Seleziona un mercato per aprire i dettagli sotto la sua scheda.", starsCalculator: "Calcolatrice Telegram Stars", starsCount: "Numero di Stars", calculationCurrency: "Valuta di calcolo", referenceEstimate: "Stima di riferimento", loadingMarket: "Caricamento dei dati di mercato…", recoveringMarket: "I dati di mercato sono temporaneamente in ripristino.", currentPrice: "Prezzo attuale", bestBuy: "Miglior acquisto", bestSell: "Migliore vendita", dayRange: "Intervallo 24 ore", livePriceChart: "Prezzo e grafico in tempo reale", realMarketData: "Dati reali di mercato", chartSync: "Sincronizzazione grafico…", addFavorite: "Aggiungi ai preferiti", removeFavorite: "Rimuovi dai preferiti" },
  de: { navLabel: "Devisenmarkt", live: "Live-Verbindung", connecting: "Verbindung wird hergestellt", waiting: "Warte auf Verbindung", favorites: "Favoriten", coreAssets: "Kernwerte", searchResults: "Suchergebnisse", activeSearch: "Aktive Märkte werden durchsucht", clearSearch: "Suche löschen", expandHint: "Wählen Sie einen Markt, um die Details direkt unter der Karte zu öffnen.", starsCalculator: "Telegram-Stars-Rechner", starsCount: "Anzahl der Stars", calculationCurrency: "Berechnungswährung", referenceEstimate: "Referenzschätzung", loadingMarket: "Marktdaten werden geladen…", recoveringMarket: "Marktdaten werden vorübergehend wiederhergestellt.", currentPrice: "Aktueller Preis", bestBuy: "Bester Kauf", bestSell: "Bester Verkauf", dayRange: "24-Stunden-Spanne", livePriceChart: "Live-Preis und Chart", realMarketData: "Echte Marktdaten", chartSync: "Chart wird synchronisiert…", addFavorite: "Zu Favoriten hinzufügen", removeFavorite: "Aus Favoriten entfernen" },
  pl: { navLabel: "Rynek walut", live: "Połączenie na żywo", connecting: "Łączenie", waiting: "Oczekiwanie na połączenie", favorites: "Ulubione", coreAssets: "Główne aktywa", searchResults: "Wyniki wyszukiwania", activeSearch: "Wyszukiwanie aktywnych rynków", clearSearch: "Wyczyść wyszukiwanie", expandHint: "Wybierz rynek, aby rozwinąć szczegóły bezpośrednio pod kartą.", starsCalculator: "Kalkulator Telegram Stars", starsCount: "Liczba Stars", calculationCurrency: "Waluta obliczeń", referenceEstimate: "Szacunek referencyjny", loadingMarket: "Ładowanie danych rynkowych…", recoveringMarket: "Dane rynkowe są tymczasowo odzyskiwane.", currentPrice: "Aktualna cena", bestBuy: "Najlepszy zakup", bestSell: "Najlepsza sprzedaż", dayRange: "Zakres 24 godzin", livePriceChart: "Cena i wykres na żywo", realMarketData: "Rzeczywiste dane rynkowe", chartSync: "Synchronizacja wykresu…", addFavorite: "Dodaj do ulubionych", removeFavorite: "Usuń z ulubionych" },
  vi: { navLabel: "Thị trường tiền tệ", live: "Kết nối trực tiếp", connecting: "Đang kết nối", waiting: "Đang chờ kết nối", favorites: "Yêu thích", coreAssets: "Tài sản chính", searchResults: "Kết quả tìm kiếm", activeSearch: "Đang tìm thị trường hoạt động", clearSearch: "Xóa tìm kiếm", expandHint: "Chọn một thị trường để mở chi tiết ngay bên dưới thẻ.", starsCalculator: "Máy tính Telegram Stars", starsCount: "Số lượng Stars", calculationCurrency: "Đơn vị tính", referenceEstimate: "Ước tính tham chiếu", loadingMarket: "Đang tải dữ liệu thị trường…", recoveringMarket: "Dữ liệu thị trường đang được khôi phục tạm thời.", currentPrice: "Giá hiện tại", bestBuy: "Giá mua tốt nhất", bestSell: "Giá bán tốt nhất", dayRange: "Phạm vi 24 giờ", livePriceChart: "Giá và biểu đồ trực tiếp", realMarketData: "Dữ liệu thị trường thực", chartSync: "Đang đồng bộ biểu đồ…", addFavorite: "Thêm vào yêu thích", removeFavorite: "Xóa khỏi yêu thích" },
};

const starsTitles: Record<DashboardLocale, string> = {
  fa: "استارز تلگرام", en: "Telegram Stars", ar: "نجوم تيليجرام", tr: "Telegram Yıldızları", ru: "Звёзды Telegram",
  es: "Estrellas de Telegram", fr: "Étoiles Telegram", pt: "Estrelas do Telegram", it: "Stelle Telegram", de: "Telegram-Sterne", pl: "Gwiazdy Telegrama", vi: "Sao Telegram",
};

const loadMoreMarkets: Record<DashboardLocale, string> = {
  fa: "مشاهدهٔ ۸ ارز بیشتر", en: "Show 8 more markets", ar: "عرض 8 عملات أخرى", tr: "8 piyasa daha göster", ru: "Показать ещё 8 рынков",
  es: "Ver 8 mercados más", fr: "Afficher 8 marchés de plus", pt: "Ver mais 8 mercados", it: "Mostra altri 8 mercati", de: "8 weitere Märkte anzeigen", pl: "Pokaż 8 kolejnych rynków", vi: "Xem thêm 8 thị trường",
};

const loadLessMarkets: Record<DashboardLocale, string> = {
  fa: "نمایش ۸ ارز کمتر", en: "Show 8 fewer markets", ar: "عرض 8 عملات أقل", tr: "8 piyasa daha az göster", ru: "Показать на 8 рынков меньше",
  es: "Ver 8 mercados menos", fr: "Afficher 8 marchés de moins", pt: "Ver 8 mercados a menos", it: "Mostra 8 mercati in meno", de: "8 Märkte weniger anzeigen", pl: "Pokaż o 8 rynków mniej", vi: "Hiển thị ít hơn 8 thị trường",
};

export function classicCryptoMarketCopyFor(locale: DashboardLocale) {
  return { ...cryptoMarketCopyFor(locale), ...extra[locale], starsTitle: starsTitles[locale], loadMoreMarkets: loadMoreMarkets[locale], loadLessMarkets: loadLessMarkets[locale] };
}
