import type { DashboardLocale } from "@/lib/dashboardI18n";

export type CryptoMarketRange = "1d" | "7d" | "30d";

export type CryptoMarketCopy = {
  eyebrow: string;
  title: string;
  subtitle: string;
  liveCurrent: string;
  liveStored: string;
  visibleAssets: string;
  conversionInfo: string;
  listTitle: string;
  listDescription: string;
  refreshList: string;
  searchPlaceholder: string;
  recovering: string;
  retry: string;
  notFound: string;
  referenceRate: string;
  globalPrice: string;
  iranPrice: string;
  dataStatus: string;
  marketReferenceRate: string;
  officialChangeUnavailable: string;
  profitLoss24h: string;
  volume: string;
  detailRecovering: string;
  starsDisclaimer: string;
  realPriceRefresh: string;
  selectChartRange: string;
  chartSource: string;
  lastRate: string;
  lastMarketUpdate: string;
  chartUnavailable: string;
  chartRecovery: string;
  chartAria: string;
  tehranTime: string;
  price: string;
  toman: string;
  chartHint: string;
  refreshAsset: string;
  ranges: Record<CryptoMarketRange, { label: string; heading: string }>;
};

const marketCopy: Record<DashboardLocale, CryptoMarketCopy> = {
  fa: {
    eyebrow: "بازار کرونوس", title: "بازار عمومی رمزارز", subtitle: "قیمت واقعی، تغییرات 24ساعته و نمودار هر دارایی را با انتخاب همان ردیف ببینید.", liveCurrent: "دادهٔ جاری · 60ث", liveStored: "دادهٔ ذخیره‌شده", visibleAssets: "دارایی قابل مشاهده", conversionInfo: "USD عمومی · تبدیل تومان با USDT/IRR", listTitle: "قیمت و نمودار دارایی‌ها", listDescription: "Telegram Stars به‌عنوان نرخ مرجع همیشه ابتدای فهرست است؛ سایر دارایی‌ها بر اساس تغییر 24ساعته مرتب می‌شوند.", refreshList: "تازه‌سازی فهرست بازار", searchPlaceholder: "جست‌وجوی نام یا نماد ارز", recovering: "دادهٔ بازار در حال بازیابی است", retry: "دریافت دوباره", notFound: "دارایی مطابق جست‌وجوی شما پیدا نشد.", referenceRate: "نرخ مرجع", globalPrice: "قیمت جهانی", iranPrice: "قیمت در ایران", dataStatus: "وضعیت داده", marketReferenceRate: "نرخ مرجع بازار", officialChangeUnavailable: "تغییر 24ساعتهٔ رسمی در دسترس نیست", profitLoss24h: "سود / زیان 24 ساعته", volume: "حجم", detailRecovering: "جزئیات تکمیلی از منبع جایگزین در حال دریافت است؛ آخرین قیمت معتبر نمایش داده می‌شود.", starsDisclaimer: "هشدار: این نرخ، قیمت مرجع Stars است و قیمت نهایی خرید در پرداخت Telegram یا فروشنده می‌تواند متفاوت باشد.", realPriceRefresh: "قیمت واقعی؛ تازه‌سازی خودکار حداکثر هر 1 دقیقه", selectChartRange: "انتخاب بازهٔ نمودار", chartSource: "منبع نمودار", lastRate: "آخرین نرخ", lastMarketUpdate: "آخرین به‌روزرسانی بازار", chartUnavailable: "نمودار {range} در این لحظه در دسترس نیست", chartRecovery: "قیمت جاری حفظ شده است؛ با تازه‌سازی بعدی دوباره دادهٔ واقعی دریافت می‌شود.", chartAria: "نمودار قیمت در بازهٔ {range}", tehranTime: "زمان تهران", price: "قیمت", toman: "تومان", chartHint: "برای دیدن زمان و قیمت دقیق، نشانگر را روی نمودار حرکت دهید.", refreshAsset: "تازه‌سازی {asset}", ranges: { "1d": { label: "24 ساعت", heading: "نمودار 24 ساعت اخیر" }, "7d": { label: "7 روز", heading: "نمودار 7 روز اخیر" }, "30d": { label: "30 روز", heading: "نمودار 30 روز اخیر" } },
  },
  en: {
    eyebrow: "KRONOS MARKET", title: "Public crypto market", subtitle: "Select any asset to view its real-time price, 24-hour change, and chart.", liveCurrent: "Current data · 60s", liveStored: "Cached data", visibleAssets: "visible assets", conversionInfo: "Public USD · Toman conversion via USDT/IRR", listTitle: "Asset prices and charts", listDescription: "Telegram Stars is pinned first as a reference rate; other assets are sorted by 24-hour change.", refreshList: "Refresh market list", searchPlaceholder: "e.g. Stars, Bitcoin, DOGE", recovering: "Market data is recovering", retry: "Retry", notFound: "No asset matches your search.", referenceRate: "Reference rate", globalPrice: "Global price", iranPrice: "Price in Iran", dataStatus: "Data status", marketReferenceRate: "Market reference rate", officialChangeUnavailable: "Official 24-hour change is unavailable", profitLoss24h: "24-hour gain / loss", volume: "Volume", detailRecovering: "Additional details are loading from a fallback source; the last valid price remains visible.", starsDisclaimer: "Notice: this is the Stars reference price. The final Telegram or seller checkout pricing may differ.", realPriceRefresh: "Real price; refreshes automatically at most every 1 minute", selectChartRange: "Select chart range", chartSource: "Chart source", lastRate: "Last rate", lastMarketUpdate: "Last market update", chartUnavailable: "The {range} chart is unavailable right now", chartRecovery: "The current price is preserved; real data will be requested again on the next refresh.", chartAria: "Price chart for {range}", tehranTime: "Tehran time", price: "Price", toman: "Toman", chartHint: "Move the pointer over the chart to view the precise time and price.", refreshAsset: "Refresh {asset}", ranges: { "1d": { label: "24 hours", heading: "Last 24 hours" }, "7d": { label: "7 days", heading: "Last 7 days" }, "30d": { label: "30 days", heading: "Last 30 days" } },
  },
  ar: {
    eyebrow: "سوق كرونوس", title: "سوق العملات الرقمية العام", subtitle: "اختر أي أصل لعرض السعر الفعلي والتغير خلال 24 ساعة والرسم البياني.", liveCurrent: "بيانات حالية · 60ث", liveStored: "بيانات محفوظة", visibleAssets: "أصول ظاهرة", conversionInfo: "USD عام · تحويل التومان عبر USDT/IRR", listTitle: "أسعار الأصول ورسومها", listDescription: "تظهر Telegram Stars أولاً كسعر مرجعي؛ وتُرتب الأصول الأخرى حسب تغير 24 ساعة.", refreshList: "تحديث قائمة السوق", searchPlaceholder: "مثال: Stars، Bitcoin، DOGE", recovering: "يتم استعادة بيانات السوق", retry: "إعادة المحاولة", notFound: "لا يوجد أصل يطابق بحثك.", referenceRate: "سعر مرجعي", globalPrice: "السعر العالمي", iranPrice: "السعر في إيران", dataStatus: "حالة البيانات", marketReferenceRate: "سعر السوق المرجعي", officialChangeUnavailable: "تغير 24 ساعة الرسمي غير متاح", profitLoss24h: "ربح / خسارة 24 ساعة", volume: "الحجم", detailRecovering: "يجري جلب التفاصيل الإضافية من مصدر بديل؛ ويظل آخر سعر صالح معروضاً.", starsDisclaimer: "سعر مرجعي للسوق، وليس سعراً مضموناً. قد يختلف سعر Telegram Stars حسب طريقة الشراء والمنصة والمنطقة.", realPriceRefresh: "سعر فعلي؛ تحديث تلقائي كل دقيقة كحد أقصى", selectChartRange: "اختيار نطاق الرسم", chartSource: "مصدر الرسم", lastRate: "آخر سعر", lastMarketUpdate: "آخر تحديث للسوق", chartUnavailable: "رسم {range} غير متاح حالياً", chartRecovery: "يُحفظ السعر الحالي وسيُطلب بيانات فعلية مجدداً عند التحديث التالي.", chartAria: "رسم السعر لنطاق {range}", tehranTime: "وقت طهران", price: "السعر", toman: "تومان", chartHint: "حرّك المؤشر فوق الرسم لعرض الوقت والسعر بدقة.", refreshAsset: "تحديث {asset}", ranges: { "1d": { label: "24 ساعة", heading: "آخر 24 ساعة" }, "7d": { label: "7 أيام", heading: "آخر 7 أيام" }, "30d": { label: "30 يوماً", heading: "آخر 30 يوماً" } },
  },
  tr: {
    eyebrow: "KRONOS PİYASA", title: "Genel kripto piyasası", subtitle: "Gerçek fiyatı, 24 saatlik değişimi ve grafiği görmek için bir varlık seçin.", liveCurrent: "Güncel veri · 60 sn", liveStored: "Önbellek verisi", visibleAssets: "görünen varlık", conversionInfo: "Genel USD · USDT/IRR ile Toman dönüşümü", listTitle: "Varlık fiyatları ve grafikleri", listDescription: "Telegram Stars referans oran olarak ilk sıradadır; diğer varlıklar 24 saatlik değişime göre sıralanır.", refreshList: "Piyasa listesini yenile", searchPlaceholder: "ör. Stars, Bitcoin, DOGE", recovering: "Piyasa verisi yenileniyor", retry: "Tekrar dene", notFound: "Aramanızla eşleşen varlık bulunamadı.", referenceRate: "Referans oran", globalPrice: "Küresel fiyat", iranPrice: "İran fiyatı", dataStatus: "Veri durumu", marketReferenceRate: "Piyasa referans oranı", officialChangeUnavailable: "Resmî 24 saatlik değişim yok", profitLoss24h: "24 saat kâr / zarar", volume: "Hacim", detailRecovering: "Ek ayrıntılar alternatif kaynaktan yükleniyor; son geçerli fiyat gösterilmeye devam eder.", starsDisclaimer: "Piyasa referans oranıdır, garanti fiyat değildir. Telegram Stars fiyatı satın alma yöntemi, platform ve bölgeye göre değişebilir.", realPriceRefresh: "Gerçek fiyat; en fazla her 1 dakikada otomatik yenilenir", selectChartRange: "Grafik aralığını seç", chartSource: "Grafik kaynağı", lastRate: "Son oran", lastMarketUpdate: "Son piyasa güncellemesi", chartUnavailable: "{range} grafiği şu anda kullanılamıyor", chartRecovery: "Mevcut fiyat korunur; sonraki yenilemede gerçek veri tekrar istenir.", chartAria: "{range} fiyat grafiği", tehranTime: "Tahran saati", price: "Fiyat", toman: "Toman", chartHint: "Kesin zaman ve fiyatı görmek için imleci grafiğin üzerinde gezdirin.", refreshAsset: "{asset} yenile", ranges: { "1d": { label: "24 saat", heading: "Son 24 saat" }, "7d": { label: "7 gün", heading: "Son 7 gün" }, "30d": { label: "30 gün", heading: "Son 30 gün" } },
  },
  ru: {
    eyebrow: "РЫНОК KRONOS", title: "Публичный крипторынок", subtitle: "Выберите актив, чтобы увидеть реальную цену, изменение за 24 часа и график.", liveCurrent: "Текущие данные · 60 с", liveStored: "Кэшированные данные", visibleAssets: "доступных активов", conversionInfo: "Публичный USD · конвертация в томан через USDT/IRR", listTitle: "Цены и графики активов", listDescription: "Telegram Stars закреплён первым как справочный курс; остальные активы отсортированы по изменению за 24 часа.", refreshList: "Обновить рынок", searchPlaceholder: "например Stars, Bitcoin, DOGE", recovering: "Рыночные данные восстанавливаются", retry: "Повторить", notFound: "По вашему запросу ничего не найдено.", referenceRate: "Справочный курс", globalPrice: "Мировая цена", iranPrice: "Цена в Иране", dataStatus: "Статус данных", marketReferenceRate: "Справочный курс рынка", officialChangeUnavailable: "Официальное изменение за 24 часа недоступно", profitLoss24h: "Прибыль / убыток за 24 часа", volume: "Объём", detailRecovering: "Дополнительные сведения загружаются из резервного источника; последняя действительная цена остаётся видимой.", starsDisclaimer: "Справочный курс рынка, не гарантированная цена. Цена Telegram Stars может различаться по способу покупки, платформе и региону.", realPriceRefresh: "Реальная цена; автоматическое обновление не реже раза в минуту", selectChartRange: "Выбрать период", chartSource: "Источник графика", lastRate: "Последний курс", lastMarketUpdate: "Последнее обновление рынка", chartUnavailable: "График за {range} сейчас недоступен", chartRecovery: "Текущая цена сохранена; реальные данные будут запрошены при следующем обновлении.", chartAria: "График цены за {range}", tehranTime: "Время Тегерана", price: "Цена", toman: "Томан", chartHint: "Наведите указатель на график, чтобы увидеть точное время и цену.", refreshAsset: "Обновить {asset}", ranges: { "1d": { label: "24 часа", heading: "Последние 24 часа" }, "7d": { label: "7 дней", heading: "Последние 7 дней" }, "30d": { label: "30 дней", heading: "Последние 30 дней" } },
  },
  es: {
    eyebrow: "MERCADO KRONOS", title: "Mercado público de criptomonedas", subtitle: "Seleccione un activo para ver su precio real, variación de 24 horas y gráfico.", liveCurrent: "Datos actuales · 60 s", liveStored: "Datos en caché", visibleAssets: "activos visibles", conversionInfo: "USD público · conversión a toman mediante USDT/IRR", listTitle: "Precios y gráficos de activos", listDescription: "Telegram Stars aparece primero como tasa de referencia; los demás activos se ordenan por variación de 24 horas.", refreshList: "Actualizar mercado", searchPlaceholder: "p. ej. Stars, Bitcoin, DOGE", recovering: "Los datos de mercado se están recuperando", retry: "Reintentar", notFound: "No hay activos que coincidan con su búsqueda.", referenceRate: "Tasa de referencia", globalPrice: "Precio global", iranPrice: "Precio en Irán", dataStatus: "Estado de los datos", marketReferenceRate: "Tasa de referencia del mercado", officialChangeUnavailable: "La variación oficial de 24 horas no está disponible", profitLoss24h: "Ganancia / pérdida de 24 horas", volume: "Volumen", detailRecovering: "Los detalles adicionales se cargan desde una fuente alternativa; se conserva el último precio válido.", starsDisclaimer: "Tasa de referencia del mercado, no precio garantizado. El precio de Telegram Stars puede variar según método de compra, plataforma y región.", realPriceRefresh: "Precio real; se actualiza automáticamente como máximo cada 1 minuto", selectChartRange: "Seleccionar periodo", chartSource: "Fuente del gráfico", lastRate: "Última tasa", lastMarketUpdate: "Última actualización del mercado", chartUnavailable: "El gráfico de {range} no está disponible ahora", chartRecovery: "Se conserva el precio actual; se solicitarán datos reales en la siguiente actualización.", chartAria: "Gráfico de precio de {range}", tehranTime: "Hora de Teherán", price: "Precio", toman: "Toman", chartHint: "Mueva el puntero sobre el gráfico para ver la hora y el precio exactos.", refreshAsset: "Actualizar {asset}", ranges: { "1d": { label: "24 horas", heading: "Últimas 24 horas" }, "7d": { label: "7 días", heading: "Últimos 7 días" }, "30d": { label: "30 días", heading: "Últimos 30 días" } },
  },
  fr: {
    eyebrow: "MARCHÉ KRONOS", title: "Marché public des cryptomonnaies", subtitle: "Sélectionnez un actif pour voir son prix réel, sa variation sur 24 heures et son graphique.", liveCurrent: "Données actuelles · 60 s", liveStored: "Données en cache", visibleAssets: "actifs visibles", conversionInfo: "USD public · conversion en toman via USDT/IRR", listTitle: "Prix et graphiques des actifs", listDescription: "Telegram Stars est épinglé en tête comme taux de référence ; les autres actifs sont triés par variation sur 24 heures.", refreshList: "Actualiser le marché", searchPlaceholder: "ex. Stars, Bitcoin, DOGE", recovering: "Les données du marché sont en cours de récupération", retry: "Réessayer", notFound: "Aucun actif ne correspond à votre recherche.", referenceRate: "Taux de référence", globalPrice: "Prix mondial", iranPrice: "Prix en Iran", dataStatus: "État des données", marketReferenceRate: "Taux de référence du marché", officialChangeUnavailable: "La variation officielle sur 24 heures est indisponible", profitLoss24h: "Gain / perte sur 24 heures", volume: "Volume", detailRecovering: "Des détails supplémentaires se chargent depuis une source de secours ; le dernier prix valide reste affiché.", starsDisclaimer: "Taux de référence du marché, et non prix garanti. Le prix Telegram Stars peut varier selon le mode d’achat, la plateforme et la région.", realPriceRefresh: "Prix réel ; actualisation automatique au plus toutes les 1 minute", selectChartRange: "Choisir la période", chartSource: "Source du graphique", lastRate: "Dernier taux", lastMarketUpdate: "Dernière mise à jour du marché", chartUnavailable: "Le graphique sur {range} est indisponible actuellement", chartRecovery: "Le prix actuel est conservé ; des données réelles seront demandées à la prochaine actualisation.", chartAria: "Graphique de prix sur {range}", tehranTime: "Heure de Téhéran", price: "Prix", toman: "Toman", chartHint: "Déplacez le pointeur sur le graphique pour voir l’heure et le prix exacts.", refreshAsset: "Actualiser {asset}", ranges: { "1d": { label: "24 heures", heading: "Dernières 24 heures" }, "7d": { label: "7 jours", heading: "7 derniers jours" }, "30d": { label: "30 jours", heading: "30 derniers jours" } },
  },
  pt: {
    eyebrow: "MERCADO KRONOS", title: "Mercado público de criptomoedas", subtitle: "Selecione um ativo para ver seu preço real, variação de 24 horas e gráfico.", liveCurrent: "Dados atuais · 60 s", liveStored: "Dados em cache", visibleAssets: "ativos visíveis", conversionInfo: "USD público · conversão para toman via USDT/IRR", listTitle: "Preços e gráficos dos ativos", listDescription: "Telegram Stars fica fixado no início como taxa de referência; os demais ativos são ordenados pela variação de 24 horas.", refreshList: "Atualizar mercado", searchPlaceholder: "ex.: Stars, Bitcoin, DOGE", recovering: "Os dados do mercado estão sendo recuperados", retry: "Tentar novamente", notFound: "Nenhum ativo corresponde à sua busca.", referenceRate: "Taxa de referência", globalPrice: "Preço global", iranPrice: "Preço no Irã", dataStatus: "Status dos dados", marketReferenceRate: "Taxa de referência do mercado", officialChangeUnavailable: "A variação oficial de 24 horas não está disponível", profitLoss24h: "Ganho / perda em 24 horas", volume: "Volume", detailRecovering: "Detalhes adicionais estão sendo carregados de uma fonte alternativa; o último preço válido permanece visível.", starsDisclaimer: "Taxa de referência do mercado, não um preço garantido. O preço do Telegram Stars pode variar conforme compra, plataforma e região.", realPriceRefresh: "Preço real; atualização automática no máximo a cada 1 minuto", selectChartRange: "Selecionar período", chartSource: "Fonte do gráfico", lastRate: "Última taxa", lastMarketUpdate: "Última atualização do mercado", chartUnavailable: "O gráfico de {range} não está disponível agora", chartRecovery: "O preço atual é preservado; dados reais serão solicitados na próxima atualização.", chartAria: "Gráfico de preço de {range}", tehranTime: "Horário de Teerã", price: "Preço", toman: "Toman", chartHint: "Mova o ponteiro sobre o gráfico para ver hora e preço precisos.", refreshAsset: "Atualizar {asset}", ranges: { "1d": { label: "24 horas", heading: "Últimas 24 horas" }, "7d": { label: "7 dias", heading: "Últimos 7 dias" }, "30d": { label: "30 dias", heading: "Últimos 30 dias" } },
  },
  it: {
    eyebrow: "MERCATO KRONOS", title: "Mercato pubblico delle criptovalute", subtitle: "Seleziona un asset per vedere prezzo reale, variazione nelle 24 ore e grafico.", liveCurrent: "Dati correnti · 60 s", liveStored: "Dati in cache", visibleAssets: "asset visibili", conversionInfo: "USD pubblico · conversione in toman tramite USDT/IRR", listTitle: "Prezzi e grafici degli asset", listDescription: "Telegram Stars è fissato in alto come tasso di riferimento; gli altri asset sono ordinati per variazione nelle 24 ore.", refreshList: "Aggiorna mercato", searchPlaceholder: "es. Stars, Bitcoin, DOGE", recovering: "I dati di mercato si stanno ripristinando", retry: "Riprova", notFound: "Nessun asset corrisponde alla ricerca.", referenceRate: "Tasso di riferimento", globalPrice: "Prezzo globale", iranPrice: "Prezzo in Iran", dataStatus: "Stato dati", marketReferenceRate: "Tasso di riferimento del mercato", officialChangeUnavailable: "La variazione ufficiale nelle 24 ore non è disponibile", profitLoss24h: "Guadagno / perdita 24 ore", volume: "Volume", detailRecovering: "I dettagli aggiuntivi vengono caricati da una fonte alternativa; l’ultimo prezzo valido resta visibile.", starsDisclaimer: "Tasso di riferimento del mercato, non prezzo garantito. Il prezzo Telegram Stars può variare per metodo di acquisto, piattaforma e regione.", realPriceRefresh: "Prezzo reale; aggiornamento automatico al massimo ogni 1 minuto", selectChartRange: "Seleziona intervallo", chartSource: "Fonte del grafico", lastRate: "Ultimo tasso", lastMarketUpdate: "Ultimo aggiornamento del mercato", chartUnavailable: "Il grafico di {range} non è disponibile al momento", chartRecovery: "Il prezzo corrente è conservato; i dati reali saranno richiesti al prossimo aggiornamento.", chartAria: "Grafico del prezzo per {range}", tehranTime: "Ora di Teheran", price: "Prezzo", toman: "Toman", chartHint: "Sposta il puntatore sul grafico per vedere ora e prezzo precisi.", refreshAsset: "Aggiorna {asset}", ranges: { "1d": { label: "24 ore", heading: "Ultime 24 ore" }, "7d": { label: "7 giorni", heading: "Ultimi 7 giorni" }, "30d": { label: "30 giorni", heading: "Ultimi 30 giorni" } },
  },
  de: {
    eyebrow: "KRONOS-MARKT", title: "Öffentlicher Kryptomarkt", subtitle: "Wählen Sie einen Vermögenswert, um den realen Preis, die 24-Stunden-Änderung und den Chart zu sehen.", liveCurrent: "Aktuelle Daten · 60 s", liveStored: "Zwischengespeicherte Daten", visibleAssets: "sichtbare Werte", conversionInfo: "Öffentlicher USD · Toman-Umrechnung über USDT/IRR", listTitle: "Preise und Charts", listDescription: "Telegram Stars ist als Referenzkurs oben angeheftet; andere Werte sind nach 24-Stunden-Änderung sortiert.", refreshList: "Marktliste aktualisieren", searchPlaceholder: "z. B. Stars, Bitcoin, DOGE", recovering: "Marktdaten werden wiederhergestellt", retry: "Erneut versuchen", notFound: "Kein Vermögenswert entspricht Ihrer Suche.", referenceRate: "Referenzkurs", globalPrice: "Weltpreis", iranPrice: "Preis im Iran", dataStatus: "Datenstatus", marketReferenceRate: "Marktreferenzkurs", officialChangeUnavailable: "Offizielle 24-Stunden-Änderung nicht verfügbar", profitLoss24h: "24-Stunden-Gewinn / Verlust", volume: "Volumen", detailRecovering: "Zusätzliche Details werden aus einer Ersatzquelle geladen; der letzte gültige Preis bleibt sichtbar.", starsDisclaimer: "Marktreferenzkurs, kein garantierter Preis. Der Telegram-Stars-Preis kann je nach Kaufmethode, Plattform und Region abweichen.", realPriceRefresh: "Realer Preis; automatische Aktualisierung höchstens jede 1 Minute", selectChartRange: "Chart-Zeitraum wählen", chartSource: "Chart-Quelle", lastRate: "Letzter Kurs", lastMarketUpdate: "Letzte Marktaktualisierung", chartUnavailable: "Der Chart für {range} ist derzeit nicht verfügbar", chartRecovery: "Der aktuelle Preis bleibt erhalten; echte Daten werden bei der nächsten Aktualisierung erneut angefordert.", chartAria: "Preischart für {range}", tehranTime: "Teheraner Zeit", price: "Preis", toman: "Toman", chartHint: "Bewegen Sie den Zeiger über den Chart, um Zeit und Preis genau zu sehen.", refreshAsset: "{asset} aktualisieren", ranges: { "1d": { label: "24 Stunden", heading: "Letzte 24 Stunden" }, "7d": { label: "7 Tage", heading: "Letzte 7 Tage" }, "30d": { label: "30 Tage", heading: "Letzte 30 Tage" } },
  },
  pl: {
    eyebrow: "RYNEK KRONOS", title: "Publiczny rynek kryptowalut", subtitle: "Wybierz aktywo, aby zobaczyć rzeczywistą cenę, zmianę z 24 godzin i wykres.", liveCurrent: "Bieżące dane · 60 s", liveStored: "Dane z pamięci podręcznej", visibleAssets: "widocznych aktywów", conversionInfo: "Publiczny USD · przeliczenie na toman przez USDT/IRR", listTitle: "Ceny i wykresy aktywów", listDescription: "Telegram Stars jest przypięty na początku jako kurs referencyjny; pozostałe aktywa są sortowane według zmiany z 24 godzin.", refreshList: "Odśwież rynek", searchPlaceholder: "np. Stars, Bitcoin, DOGE", recovering: "Dane rynkowe są odzyskiwane", retry: "Spróbuj ponownie", notFound: "Brak aktywów pasujących do wyszukiwania.", referenceRate: "Kurs referencyjny", globalPrice: "Cena globalna", iranPrice: "Cena w Iranie", dataStatus: "Stan danych", marketReferenceRate: "Kurs referencyjny rynku", officialChangeUnavailable: "Oficjalna zmiana z 24 godzin jest niedostępna", profitLoss24h: "Zysk / strata 24 godziny", volume: "Wolumen", detailRecovering: "Dodatkowe dane są ładowane ze źródła zastępczego; ostatnia prawidłowa cena pozostaje widoczna.", starsDisclaimer: "Kurs referencyjny rynku, nie gwarantowana cena. Cena Telegram Stars może różnić się zależnie od metody zakupu, platformy i regionu.", realPriceRefresh: "Rzeczywista cena; automatyczne odświeżanie najwyżej co 1 minutę", selectChartRange: "Wybierz zakres wykresu", chartSource: "Źródło wykresu", lastRate: "Ostatni kurs", lastMarketUpdate: "Ostatnia aktualizacja rynku", chartUnavailable: "Wykres dla {range} jest obecnie niedostępny", chartRecovery: "Bieżąca cena jest zachowana; prawdziwe dane zostaną pobrane przy następnym odświeżeniu.", chartAria: "Wykres ceny dla {range}", tehranTime: "Czas w Teheranie", price: "Cena", toman: "Toman", chartHint: "Przesuń wskaźnik nad wykres, aby zobaczyć dokładny czas i cenę.", refreshAsset: "Odśwież {asset}", ranges: { "1d": { label: "24 godziny", heading: "Ostatnie 24 godziny" }, "7d": { label: "7 dni", heading: "Ostatnie 7 dni" }, "30d": { label: "30 dni", heading: "Ostatnie 30 dni" } },
  },
  vi: {
    eyebrow: "THỊ TRƯỜNG KRONOS", title: "Thị trường tiền mã hóa công khai", subtitle: "Chọn một tài sản để xem giá thực, biến động 24 giờ và biểu đồ.", liveCurrent: "Dữ liệu hiện tại · 60 giây", liveStored: "Dữ liệu đã lưu", visibleAssets: "tài sản hiển thị", conversionInfo: "USD công khai · quy đổi toman qua USDT/IRR", listTitle: "Giá và biểu đồ tài sản", listDescription: "Telegram Stars được ghim đầu tiên như tỷ giá tham chiếu; các tài sản khác được sắp xếp theo biến động 24 giờ.", refreshList: "Làm mới thị trường", searchPlaceholder: "ví dụ: Stars, Bitcoin, DOGE", recovering: "Dữ liệu thị trường đang được khôi phục", retry: "Thử lại", notFound: "Không có tài sản nào khớp với tìm kiếm của bạn.", referenceRate: "Tỷ giá tham chiếu", globalPrice: "Giá toàn cầu", iranPrice: "Giá tại Iran", dataStatus: "Trạng thái dữ liệu", marketReferenceRate: "Tỷ giá tham chiếu thị trường", officialChangeUnavailable: "Không có biến động chính thức trong 24 giờ", profitLoss24h: "Lãi / lỗ 24 giờ", volume: "Khối lượng", detailRecovering: "Thông tin bổ sung đang tải từ nguồn thay thế; giá hợp lệ gần nhất vẫn hiển thị.", starsDisclaimer: "Tỷ giá tham chiếu thị trường, không phải giá đảm bảo. Giá Telegram Stars có thể khác theo phương thức mua, nền tảng và khu vực.", realPriceRefresh: "Giá thực; tự động làm mới tối đa mỗi 1 phút", selectChartRange: "Chọn phạm vi biểu đồ", chartSource: "Nguồn biểu đồ", lastRate: "Tỷ giá gần nhất", lastMarketUpdate: "Cập nhật thị trường gần nhất", chartUnavailable: "Biểu đồ {range} hiện chưa khả dụng", chartRecovery: "Giá hiện tại được giữ lại; dữ liệu thực sẽ được yêu cầu lại ở lần làm mới tiếp theo.", chartAria: "Biểu đồ giá trong {range}", tehranTime: "Giờ Tehran", price: "Giá", toman: "Toman", chartHint: "Di chuyển con trỏ trên biểu đồ để xem thời gian và giá chính xác.", refreshAsset: "Làm mới {asset}", ranges: { "1d": { label: "24 giờ", heading: "24 giờ qua" }, "7d": { label: "7 ngày", heading: "7 ngày qua" }, "30d": { label: "30 ngày", heading: "30 ngày qua" } },
  },
};

export function cryptoMarketCopyFor(locale: DashboardLocale): CryptoMarketCopy {
  return marketCopy[locale];
}
