import type { DashboardLocale } from "./dashboardI18n";

export type DashboardNotificationDeliveryCopy = {
  eyebrow: string;
  title: string;
  description: string;
  enabled: string;
  disabled: string;
  enabledHint: string;
  disabledHint: string;
  aria: string;
  loadError: string;
};

export const dashboardNotificationDeliveryCopy: Record<DashboardLocale, DashboardNotificationDeliveryCopy> = {
  fa: { eyebrow: "مسیر تحویل", title: "کانال تحویل اعلان‌ها", description: "همهٔ رویدادها ابتدا در Mini App ثبت می‌شوند. در صورت فعال‌سازی، نسخهٔ خصوصی رویدادهای مجاز نیز به گفتگوی ربات ارسال می‌شود.", enabled: "Mini App و گفتگوی خصوصی ربات", disabled: "فقط Mini App", enabledHint: "نسخهٔ خصوصی برای رویدادهای مجاز فعال است", disabledHint: "پیام خصوصی از ربات ارسال نمی‌شود", aria: "ارسال به گفتگوی خصوصی ربات", loadError: "دریافت تنظیم کانال تحویل ناموفق بود. لطفاً دوباره تلاش کنید." },
  en: { eyebrow: "DELIVERY CHANNEL", title: "Notification delivery", description: "Events are recorded in the Mini App first. When enabled, eligible events are also delivered in a private bot chat.", enabled: "Mini App and private bot chat", disabled: "Mini App only", enabledHint: "Private delivery is enabled for eligible events", disabledHint: "The bot will not send private messages", aria: "Send to private bot chat", loadError: "Could not load the delivery setting. Please try again." },
  ar: { eyebrow: "قناة التسليم", title: "تسليم الإشعارات", description: "تُسجل الأحداث أولاً في التطبيق المصغر. عند التفعيل، تُرسل الأحداث المؤهلة أيضاً إلى محادثة خاصة مع البوت.", enabled: "التطبيق المصغر ومحادثة البوت الخاصة", disabled: "التطبيق المصغر فقط", enabledHint: "التسليم الخاص مفعّل للأحداث المؤهلة", disabledHint: "لن يرسل البوت رسائل خاصة", aria: "الإرسال إلى محادثة البوت الخاصة", loadError: "تعذر تحميل إعداد التسليم. حاول مرة أخرى." },
  tr: { eyebrow: "TESLİMAT KANALI", title: "Bildirim teslimi", description: "Olaylar önce Mini App içinde kaydedilir. Etkinleştirildiğinde uygun olaylar botun özel sohbetine de gönderilir.", enabled: "Mini App ve özel bot sohbeti", disabled: "Yalnızca Mini App", enabledHint: "Uygun olaylar için özel teslim etkin", disabledHint: "Bot özel mesaj göndermez", aria: "Özel bot sohbetine gönder", loadError: "Teslim ayarı yüklenemedi. Lütfen tekrar deneyin." },
  ru: { eyebrow: "КАНАЛ ДОСТАВКИ", title: "Доставка уведомлений", description: "События сначала сохраняются в Mini App. При включении подходящие события также отправляются в личный чат с ботом.", enabled: "Mini App и личный чат с ботом", disabled: "Только Mini App", enabledHint: "Личная доставка включена для подходящих событий", disabledHint: "Бот не будет отправлять личные сообщения", aria: "Отправлять в личный чат с ботом", loadError: "Не удалось загрузить настройку доставки. Повторите попытку." },
  es: { eyebrow: "CANAL DE ENTREGA", title: "Entrega de notificaciones", description: "Los eventos se registran primero en Mini App. Al activarlo, los eventos aptos también llegan al chat privado del bot.", enabled: "Mini App y chat privado del bot", disabled: "Solo Mini App", enabledHint: "La entrega privada está activada para eventos aptos", disabledHint: "El bot no enviará mensajes privados", aria: "Enviar al chat privado del bot", loadError: "No se pudo cargar el ajuste de entrega. Inténtalo de nuevo." },
  fr: { eyebrow: "CANAL DE DIFFUSION", title: "Livraison des notifications", description: "Les événements sont d’abord enregistrés dans la Mini App. Lorsqu’elle est activée, les événements éligibles sont aussi envoyés dans un chat privé avec le bot.", enabled: "Mini App et chat privé du bot", disabled: "Mini App uniquement", enabledHint: "La livraison privée est activée pour les événements éligibles", disabledHint: "Le bot n’enverra pas de messages privés", aria: "Envoyer au chat privé du bot", loadError: "Impossible de charger le réglage de livraison. Réessayez." },
  pt: { eyebrow: "CANAL DE ENTREGA", title: "Entrega de notificações", description: "Os eventos são registados primeiro na Mini App. Quando ativado, os eventos elegíveis também são enviados para a conversa privada do bot.", enabled: "Mini App e conversa privada do bot", disabled: "Apenas Mini App", enabledHint: "A entrega privada está ativa para eventos elegíveis", disabledHint: "O bot não enviará mensagens privadas", aria: "Enviar para a conversa privada do bot", loadError: "Não foi possível carregar a definição de entrega. Tente novamente." },
  it: { eyebrow: "CANALE DI CONSEGNA", title: "Consegna delle notifiche", description: "Gli eventi vengono prima registrati nella Mini App. Se attivata, gli eventi idonei vengono inviati anche nella chat privata del bot.", enabled: "Mini App e chat privata del bot", disabled: "Solo Mini App", enabledHint: "La consegna privata è attiva per gli eventi idonei", disabledHint: "Il bot non invierà messaggi privati", aria: "Invia alla chat privata del bot", loadError: "Impossibile caricare l’impostazione di consegna. Riprova." },
  de: { eyebrow: "ZUSTELLKANAL", title: "Benachrichtigungszustellung", description: "Ereignisse werden zuerst in der Mini App erfasst. Wenn aktiviert, werden geeignete Ereignisse auch in einen privaten Bot-Chat gesendet.", enabled: "Mini App und privater Bot-Chat", disabled: "Nur Mini App", enabledHint: "Private Zustellung ist für geeignete Ereignisse aktiv", disabledHint: "Der Bot sendet keine privaten Nachrichten", aria: "An privaten Bot-Chat senden", loadError: "Die Zustelleinstellung konnte nicht geladen werden. Bitte erneut versuchen." },
  pl: { eyebrow: "KANAŁ DOSTARCZANIA", title: "Dostarczanie powiadomień", description: "Zdarzenia są najpierw zapisywane w Mini App. Po włączeniu kwalifikujące się zdarzenia trafiają również na prywatny czat z botem.", enabled: "Mini App i prywatny czat z botem", disabled: "Tylko Mini App", enabledHint: "Prywatne dostarczanie jest aktywne dla kwalifikujących się zdarzeń", disabledHint: "Bot nie będzie wysyłać prywatnych wiadomości", aria: "Wyślij na prywatny czat z botem", loadError: "Nie udało się wczytać ustawienia dostarczania. Spróbuj ponownie." },
  vi: { eyebrow: "KÊNH GỬI", title: "Gửi thông báo", description: "Sự kiện được ghi nhận trước trong Mini App. Khi bật, các sự kiện phù hợp cũng được gửi tới cuộc trò chuyện riêng với bot.", enabled: "Mini App và trò chuyện riêng với bot", disabled: "Chỉ Mini App", enabledHint: "Đã bật gửi riêng cho các sự kiện phù hợp", disabledHint: "Bot sẽ không gửi tin nhắn riêng", aria: "Gửi tới trò chuyện riêng với bot", loadError: "Không thể tải cài đặt gửi. Vui lòng thử lại." },
};
