import type { DashboardLocale } from "./dashboardI18n";

export type DashboardNotificationCopy = {
  nav: string;
  eyebrow: string;
  title: string;
  description: string;
  markAll: string;
  markRead: string;
  read: string;
  unread: string;
  empty: string;
  loading: string;
  error: string;
  unreadCount: (count: string) => string;
  groupFilter: string;
  eventFilter: string;
  allGroups: string;
  allEvents: string;
  roleChange: string;
  groupEvent: string;
  filterReset: string;
  markedRead: string;
  markedAllRead: string;
  unknownGroup: string;
};

const copy: Record<DashboardLocale, DashboardNotificationCopy> = {
  fa: { nav: "اعلان‌ها", eyebrow: "مرکز اعلان", title: "رویدادهای مهم شما", description: "تغییرات مقام و رویدادهای مهم گروه را در همین‌جا دنبال کنید.", markAll: "همه را خوانده‌شده کن", markRead: "خوانده‌شده کن", read: "خوانده‌شده", unread: "خوانده‌نشده", empty: "اعلان تازه‌ای برای نمایش وجود ندارد.", loading: "در حال دریافت اعلان‌ها…", error: "دریافت اعلان‌ها انجام نشد.", unreadCount: count => `${count} اعلان خوانده‌نشده`, groupFilter: "فیلتر گروه", eventFilter: "نوع رویداد", allGroups: "همهٔ گروه‌ها", allEvents: "همهٔ رویدادها", roleChange: "تغییر مقام", groupEvent: "رویداد گروه", filterReset: "حذف فیلترها", markedRead: "اعلان خوانده‌شده شد.", unknownGroup: "گروه ناشناخته", markedAllRead: "همهٔ اعلان‌ها خوانده‌شده شدند." },
  en: { nav: "Notifications", eyebrow: "NOTIFICATION CENTER", title: "Your important events", description: "Follow role changes and important group events in one place.", markAll: "Mark all as read", markRead: "Mark as read", read: "Read", unread: "Unread", empty: "There are no new notifications to display.", loading: "Loading notifications…", error: "Notifications could not be loaded.", unreadCount: count => `${count} unread notifications`, groupFilter: "Group", eventFilter: "Event type", allGroups: "All groups", allEvents: "All events", roleChange: "Role change", groupEvent: "Group event", filterReset: "Clear filters", markedRead: "Notification marked as read.", unknownGroup: "Unknown group", markedAllRead: "All notifications marked as read." },
  ar: { nav: "الإشعارات", eyebrow: "مركز الإشعارات", title: "أحداثك المهمة", description: "تابع تغييرات الأدوار وأحداث المجموعة المهمة من مكان واحد.", markAll: "تحديد الكل كمقروء", markRead: "تحديد كمقروء", read: "مقروء", unread: "غير مقروء", empty: "لا توجد إشعارات جديدة للعرض.", loading: "جارٍ تحميل الإشعارات…", error: "تعذر تحميل الإشعارات.", unreadCount: count => `${count} إشعارات غير مقروءة`, groupFilter: "المجموعة", eventFilter: "نوع الحدث", allGroups: "كل المجموعات", allEvents: "كل الأحداث", roleChange: "تغيير الدور", groupEvent: "حدث المجموعة", filterReset: "مسح الفلاتر", markedRead: "تم تحديد الإشعار كمقروء.", unknownGroup: "مجموعة غير معروفة", markedAllRead: "تم تحديد كل الإشعارات كمقروءة." },
  tr: { nav: "Bildirimler", eyebrow: "BİLDİRİM MERKEZİ", title: "Önemli etkinlikleriniz", description: "Rol değişikliklerini ve önemli grup etkinliklerini tek yerde takip edin.", markAll: "Tümünü okundu olarak işaretle", markRead: "Okundu olarak işaretle", read: "Okundu", unread: "Okunmadı", empty: "Görüntülenecek yeni bildirim yok.", loading: "Bildirimler yükleniyor…", error: "Bildirimler yüklenemedi.", unreadCount: count => `${count} okunmamış bildirim`, groupFilter: "Grup", eventFilter: "Etkinlik türü", allGroups: "Tüm gruplar", allEvents: "Tüm etkinlikler", roleChange: "Rol değişikliği", groupEvent: "Grup etkinliği", filterReset: "Filtreleri temizle", markedRead: "Bildirim okundu olarak işaretlendi.", unknownGroup: "Bilinmeyen grup", markedAllRead: "Tüm bildirimler okundu olarak işaretlendi." },
  ru: { nav: "Уведомления", eyebrow: "ЦЕНТР УВЕДОМЛЕНИЙ", title: "Важные события", description: "Следите за изменениями ролей и важными событиями групп в одном месте.", markAll: "Отметить всё прочитанным", markRead: "Отметить прочитанным", read: "Прочитано", unread: "Не прочитано", empty: "Новых уведомлений нет.", loading: "Загрузка уведомлений…", error: "Не удалось загрузить уведомления.", unreadCount: count => `${count} непрочитанных уведомлений`, groupFilter: "Группа", eventFilter: "Тип события", allGroups: "Все группы", allEvents: "Все события", roleChange: "Изменение роли", groupEvent: "Событие группы", filterReset: "Очистить фильтры", markedRead: "Уведомление отмечено как прочитанное.", unknownGroup: "Неизвестная группа", markedAllRead: "Все уведомления отмечены как прочитанные." },
  es: { nav: "Notificaciones", eyebrow: "CENTRO DE NOTIFICACIONES", title: "Tus eventos importantes", description: "Sigue los cambios de roles y los eventos importantes del grupo en un solo lugar.", markAll: "Marcar todo como leído", markRead: "Marcar como leído", read: "Leído", unread: "No leído", empty: "No hay notificaciones nuevas.", loading: "Cargando notificaciones…", error: "No se pudieron cargar las notificaciones.", unreadCount: count => `${count} notificaciones sin leer`, groupFilter: "Grupo", eventFilter: "Tipo de evento", allGroups: "Todos los grupos", allEvents: "Todos los eventos", roleChange: "Cambio de rol", groupEvent: "Evento del grupo", filterReset: "Borrar filtros", markedRead: "Notificación marcada como leída.", unknownGroup: "Grupo desconocido", markedAllRead: "Todas las notificaciones fueron marcadas como leídas." },
  fr: { nav: "Notifications", eyebrow: "CENTRE DE NOTIFICATIONS", title: "Vos événements importants", description: "Suivez les changements de rôle et les événements importants du groupe au même endroit.", markAll: "Tout marquer comme lu", markRead: "Marquer comme lu", read: "Lu", unread: "Non lu", empty: "Aucune nouvelle notification.", loading: "Chargement des notifications…", error: "Impossible de charger les notifications.", unreadCount: count => `${count} notifications non lues`, groupFilter: "Groupe", eventFilter: "Type d’événement", allGroups: "Tous les groupes", allEvents: "Tous les événements", roleChange: "Changement de rôle", groupEvent: "Événement du groupe", filterReset: "Effacer les filtres", markedRead: "Notification marquée comme lue.", unknownGroup: "Groupe inconnu", markedAllRead: "Toutes les notifications ont été marquées comme lues." },
  pt: { nav: "Notificações", eyebrow: "CENTRO DE NOTIFICAÇÕES", title: "Seus eventos importantes", description: "Acompanhe mudanças de função e eventos importantes do grupo em um só lugar.", markAll: "Marcar tudo como lido", markRead: "Marcar como lido", read: "Lido", unread: "Não lido", empty: "Não há novas notificações.", loading: "Carregando notificações…", error: "Não foi possível carregar as notificações.", unreadCount: count => `${count} notificações não lidas`, groupFilter: "Grupo", eventFilter: "Tipo de evento", allGroups: "Todos os grupos", allEvents: "Todos os eventos", roleChange: "Mudança de função", groupEvent: "Evento do grupo", filterReset: "Limpar filtros", markedRead: "Notificação marcada como lida.", unknownGroup: "Grupo desconhecido", markedAllRead: "Todas as notificações foram marcadas como lidas." },
  it: { nav: "Notifiche", eyebrow: "CENTRO NOTIFICHE", title: "I tuoi eventi importanti", description: "Segui i cambiamenti di ruolo e gli eventi importanti del gruppo in un unico spazio.", markAll: "Segna tutto come letto", markRead: "Segna come letto", read: "Letto", unread: "Non letto", empty: "Non ci sono nuove notifiche.", loading: "Caricamento notifiche…", error: "Impossibile caricare le notifiche.", unreadCount: count => `${count} notifiche non lette`, groupFilter: "Gruppo", eventFilter: "Tipo di evento", allGroups: "Tutti i gruppi", allEvents: "Tutti gli eventi", roleChange: "Cambio ruolo", groupEvent: "Evento del gruppo", filterReset: "Cancella filtri", markedRead: "Notifica segnata come letta.", unknownGroup: "Gruppo sconosciuto", markedAllRead: "Tutte le notifiche sono state segnate come lette." },
  de: { nav: "Benachrichtigungen", eyebrow: "BENACHRICHTIGUNGSZENTRUM", title: "Ihre wichtigen Ereignisse", description: "Verfolgen Sie Rollenänderungen und wichtige Gruppenereignisse an einem Ort.", markAll: "Alle als gelesen markieren", markRead: "Als gelesen markieren", read: "Gelesen", unread: "Ungelesen", empty: "Keine neuen Benachrichtigungen vorhanden.", loading: "Benachrichtigungen werden geladen…", error: "Benachrichtigungen konnten nicht geladen werden.", unreadCount: count => `${count} ungelesene Benachrichtigungen`, groupFilter: "Gruppe", eventFilter: "Ereignistyp", allGroups: "Alle Gruppen", allEvents: "Alle Ereignisse", roleChange: "Rollenänderung", groupEvent: "Gruppenereignis", filterReset: "Filter löschen", markedRead: "Benachrichtigung als gelesen markiert.", unknownGroup: "Unbekannte Gruppe", markedAllRead: "Alle Benachrichtigungen als gelesen markiert." },
  pl: { nav: "Powiadomienia", eyebrow: "CENTRUM POWIADOMIEŃ", title: "Twoje ważne wydarzenia", description: "Śledź zmiany ról i ważne wydarzenia grup w jednym miejscu.", markAll: "Oznacz wszystkie jako przeczytane", markRead: "Oznacz jako przeczytane", read: "Przeczytane", unread: "Nieprzeczytane", empty: "Brak nowych powiadomień.", loading: "Ładowanie powiadomień…", error: "Nie udało się załadować powiadomień.", unreadCount: count => `${count} nieprzeczytanych powiadomień`, groupFilter: "Grupa", eventFilter: "Typ wydarzenia", allGroups: "Wszystkie grupy", allEvents: "Wszystkie wydarzenia", roleChange: "Zmiana roli", groupEvent: "Wydarzenie grupy", filterReset: "Wyczyść filtry", markedRead: "Powiadomienie oznaczono jako przeczytane.", unknownGroup: "Nieznana grupa", markedAllRead: "Wszystkie powiadomienia oznaczono jako przeczytane." },
  vi: { nav: "Thông báo", eyebrow: "TRUNG TÂM THÔNG BÁO", title: "Sự kiện quan trọng của bạn", description: "Theo dõi thay đổi vai trò và sự kiện quan trọng của nhóm tại một nơi.", markAll: "Đánh dấu tất cả đã đọc", markRead: "Đánh dấu đã đọc", read: "Đã đọc", unread: "Chưa đọc", empty: "Không có thông báo mới.", loading: "Đang tải thông báo…", error: "Không thể tải thông báo.", unreadCount: count => `${count} thông báo chưa đọc`, groupFilter: "Nhóm", eventFilter: "Loại sự kiện", allGroups: "Tất cả nhóm", allEvents: "Tất cả sự kiện", roleChange: "Thay đổi vai trò", groupEvent: "Sự kiện nhóm", filterReset: "Xóa bộ lọc", markedRead: "Đã đánh dấu thông báo là đã đọc.", unknownGroup: "Nhóm không xác định", markedAllRead: "Đã đánh dấu tất cả thông báo là đã đọc." },
};

export function dashboardNotificationCopy(locale: DashboardLocale) {
  return copy[locale];
}
