import type { DashboardLocale } from "./dashboardI18n";

type GroupFormCopy = {
  empty: string; close: string; description: string; templateTitle: string; formats: string; formatsExample: string; variables: string; variablesExample: string; readOnly: string;
  welcome: string; goodbye: string; antiSpam: string; antiRaid: string; floodLimit: string; floodWindow: string; duplicateLimit: string; warningLimit: string; rules: string; save: string; saved: string;
};

const tokens = "{user_mention}, {user_name}, {user_id}, {numeric_user_id}, {group_link}, {group_rules}, {group_name}, {date_time}.";
const markdown = "**bold**, *italic*, > quote, ~~strikethrough~~, ||spoiler||, __underline__, `code`.";

const en: GroupFormCopy = { empty: "Select a group to configure.", close: "Close group settings", description: "Welcome and goodbye templates support local dates, Telegram formatting, and variables.", templateTitle: "Templates and variables", formats: "Formats: bold, italic, quote, strikethrough, spoiler, underline, and code.", formatsExample: markdown, variables: "Variables: user mention, user name, user ID, numeric user ID, group link, group rules, group name, date and time fields.", variablesExample: tokens, readOnly: "You can view this group, but only the group owner and administrators can change its settings.", welcome: "Welcome message", goodbye: "Goodbye message", antiSpam: "Anti-spam", antiRaid: "Anti-raid", floodLimit: "Message limit", floodWindow: "Window (seconds)", duplicateLimit: "Duplicate limit", warningLimit: "Warning limit", rules: "Group rules", save: "Save settings", saved: "Group settings saved." };
const fa: GroupFormCopy = { empty: "برای تنظیم، یک گروه انتخاب کنید.", close: "بستن تنظیمات گروه", description: "قالب‌های خوش‌آمد و خداحافظی از تاریخ محلی، قالب‌بندی تلگرام و متغیرها پشتیبانی می‌کنند.", templateTitle: "قالب و متغیرها", formats: "قالب‌ها: بولد، ایتالیک، نقل‌قول، خط‌خورده، اسپویلر، زیرخط و کد.", formatsExample: "**بولد**، *ایتالیک*، > نقل‌قول، ~~خط‌خورده~~، ||اسپویلر||، __زیرخط__، `کد`.", variables: "متغیرها: منشن کاربر، نام کاربر، شناسه کاربر، شناسه عددی، لینک گروه، قوانین گروه، نام گروه، تاریخ شمسی و میلادی، و ساعت کوتاه یا کامل.", variablesExample: "{منشن_کاربر}، {نام_کاربر}، {آیدی_کاربر}، {آیدی_عددی_کاربر}، {لینک_گروه}، {قوانین_گروه}، {نام_گروه}، {تاریخ_شمسی}، {تاریخ_میلادی}، {ساعت_دقیقه}، {ساعت_دقیقه_ثانیه}.", readOnly: "شما اجازهٔ مشاهدهٔ این گروه را دارید؛ تغییر تنظیمات فقط برای مالک و مدیران گروه فعال است.", welcome: "پیام خوش‌آمد", goodbye: "پیام خداحافظی", antiSpam: "ضداسپم", antiRaid: "ضد رید", floodLimit: "سقف پیام", floodWindow: "پنجره (ثانیه)", duplicateLimit: "سقف تکرار مشابه", warningLimit: "سقف اخطار", rules: "قوانین گروه", save: "ذخیره تنظیمات", saved: "تنظیمات گروه ذخیره شد." };
const ar: GroupFormCopy = { empty: "اختر مجموعة لإعدادها.", close: "إغلاق إعدادات المجموعة", description: "تدعم قوالب الترحيب والوداع التواريخ المحلية وتنسيق تيليجرام والمتغيرات.", templateTitle: "القوالب والمتغيرات", formats: "التنسيقات: عريض ومائل واقتباس وشطب ومخفي وتسطير وكود.", formatsExample: markdown, variables: "المتغيرات: منشن المستخدم واسمه ومعرفه والرابط والقواعد واسم المجموعة والتاريخ والوقت.", variablesExample: tokens, readOnly: "يمكنك عرض هذه المجموعة، لكن المالك والمشرفين فقط يمكنهم تغيير إعداداتها.", welcome: "رسالة الترحيب", goodbye: "رسالة الوداع", antiSpam: "مكافحة الإزعاج", antiRaid: "مكافحة الغارات", floodLimit: "حد الرسائل", floodWindow: "النافذة (ثوانٍ)", duplicateLimit: "حد التكرار", warningLimit: "حد التحذيرات", rules: "قواعد المجموعة", save: "حفظ الإعدادات", saved: "تم حفظ إعدادات المجموعة." };
const tr: GroupFormCopy = { empty: "Yapılandırmak için bir grup seçin.", close: "Grup ayarlarını kapat", description: "Karşılama ve veda şablonları yerel tarihleri, Telegram biçimlendirmesini ve değişkenleri destekler.", templateTitle: "Şablonlar ve değişkenler", formats: "Biçimler: kalın, italik, alıntı, üstü çizili, spoiler, altı çizili ve kod.", formatsExample: markdown, variables: "Değişkenler: kullanıcı etiketi, adı, kimliği, grup bağlantısı, kuralları, grup adı, tarih ve saat.", variablesExample: tokens, readOnly: "Bu grubu görüntüleyebilirsiniz; ayarları yalnızca grup sahibi ve yöneticiler değiştirebilir.", welcome: "Karşılama mesajı", goodbye: "Veda mesajı", antiSpam: "Spam koruması", antiRaid: "Baskın koruması", floodLimit: "Mesaj sınırı", floodWindow: "Pencere (saniye)", duplicateLimit: "Yinelenen ileti sınırı", warningLimit: "Uyarı sınırı", rules: "Grup kuralları", save: "Ayarları kaydet", saved: "Grup ayarları kaydedildi." };
const ru: GroupFormCopy = { empty: "Выберите группу для настройки.", close: "Закрыть настройки группы", description: "Шаблоны приветствия и прощания поддерживают локальные даты, форматирование Telegram и переменные.", templateTitle: "Шаблоны и переменные", formats: "Форматы: жирный, курсив, цитата, зачёркнутый, спойлер, подчёркнутый и код.", formatsExample: markdown, variables: "Переменные: упоминание, имя и ID пользователя, ссылка, правила и имя группы, дата и время.", variablesExample: tokens, readOnly: "Вы можете просматривать группу, но изменять настройки могут только владелец и администраторы.", welcome: "Приветственное сообщение", goodbye: "Прощальное сообщение", antiSpam: "Антиспам", antiRaid: "Защита от рейдов", floodLimit: "Лимит сообщений", floodWindow: "Окно (сек.)", duplicateLimit: "Лимит повторов", warningLimit: "Лимит предупреждений", rules: "Правила группы", save: "Сохранить настройки", saved: "Настройки группы сохранены." };
const es: GroupFormCopy = { empty: "Selecciona un grupo para configurarlo.", close: "Cerrar ajustes del grupo", description: "Las plantillas de bienvenida y despedida admiten fechas locales, formato de Telegram y variables.", templateTitle: "Plantillas y variables", formats: "Formatos: negrita, cursiva, cita, tachado, spoiler, subrayado y código.", formatsExample: markdown, variables: "Variables: mención, nombre e ID del usuario, enlace, reglas y nombre del grupo, fecha y hora.", variablesExample: tokens, readOnly: "Puedes ver este grupo, pero solo el propietario y los administradores pueden cambiar sus ajustes.", welcome: "Mensaje de bienvenida", goodbye: "Mensaje de despedida", antiSpam: "Antispam", antiRaid: "Antirraid", floodLimit: "Límite de mensajes", floodWindow: "Ventana (segundos)", duplicateLimit: "Límite de duplicados", warningLimit: "Límite de advertencias", rules: "Reglas del grupo", save: "Guardar ajustes", saved: "Ajustes del grupo guardados." };
const fr: GroupFormCopy = { empty: "Sélectionnez un groupe à configurer.", close: "Fermer les paramètres du groupe", description: "Les modèles de bienvenue et d’au revoir prennent en charge les dates locales, le formatage Telegram et les variables.", templateTitle: "Modèles et variables", formats: "Formats : gras, italique, citation, barré, spoiler, souligné et code.", formatsExample: markdown, variables: "Variables : mention, nom et identifiant de l’utilisateur, lien, règles et nom du groupe, date et heure.", variablesExample: tokens, readOnly: "Vous pouvez consulter ce groupe, mais seuls le propriétaire et les administrateurs peuvent modifier ses paramètres.", welcome: "Message de bienvenue", goodbye: "Message d’au revoir", antiSpam: "Anti-spam", antiRaid: "Anti-raid", floodLimit: "Limite de messages", floodWindow: "Fenêtre (secondes)", duplicateLimit: "Limite des doublons", warningLimit: "Limite d’avertissements", rules: "Règles du groupe", save: "Enregistrer les paramètres", saved: "Paramètres du groupe enregistrés." };
const pt: GroupFormCopy = { empty: "Selecione um grupo para configurar.", close: "Fechar configurações do grupo", description: "Os modelos de boas-vindas e despedida aceitam datas locais, formatação do Telegram e variáveis.", templateTitle: "Modelos e variáveis", formats: "Formatos: negrito, itálico, citação, tachado, spoiler, sublinhado e código.", formatsExample: markdown, variables: "Variáveis: menção, nome e ID do usuário, link, regras e nome do grupo, data e hora.", variablesExample: tokens, readOnly: "Você pode ver este grupo, mas apenas o proprietário e os administradores podem alterar as configurações.", welcome: "Mensagem de boas-vindas", goodbye: "Mensagem de despedida", antiSpam: "Antispam", antiRaid: "Antiraid", floodLimit: "Limite de mensagens", floodWindow: "Janela (segundos)", duplicateLimit: "Limite de duplicados", warningLimit: "Limite de avisos", rules: "Regras do grupo", save: "Salvar configurações", saved: "Configurações do grupo salvas." };
const it: GroupFormCopy = { empty: "Seleziona un gruppo da configurare.", close: "Chiudi impostazioni gruppo", description: "I modelli di benvenuto e addio supportano date locali, formattazione Telegram e variabili.", templateTitle: "Modelli e variabili", formats: "Formati: grassetto, corsivo, citazione, barrato, spoiler, sottolineato e codice.", formatsExample: markdown, variables: "Variabili: menzione, nome e ID utente, link, regole e nome del gruppo, data e ora.", variablesExample: tokens, readOnly: "Puoi visualizzare questo gruppo, ma solo proprietario e amministratori possono modificarne le impostazioni.", welcome: "Messaggio di benvenuto", goodbye: "Messaggio di addio", antiSpam: "Anti-spam", antiRaid: "Anti-raid", floodLimit: "Limite messaggi", floodWindow: "Finestra (secondi)", duplicateLimit: "Limite duplicati", warningLimit: "Limite avvisi", rules: "Regole del gruppo", save: "Salva impostazioni", saved: "Impostazioni del gruppo salvate." };
const de: GroupFormCopy = { empty: "Wähle eine Gruppe zur Konfiguration aus.", close: "Gruppeneinstellungen schließen", description: "Willkommens- und Abschiedsvorlagen unterstützen lokale Daten, Telegram-Formatierung und Variablen.", templateTitle: "Vorlagen und Variablen", formats: "Formate: fett, kursiv, Zitat, durchgestrichen, Spoiler, unterstrichen und Code.", formatsExample: markdown, variables: "Variablen: Erwähnung, Name und ID des Nutzers, Gruppenlink, Regeln, Gruppenname, Datum und Uhrzeit.", variablesExample: tokens, readOnly: "Du kannst diese Gruppe ansehen; nur Eigentümer und Administratoren können die Einstellungen ändern.", welcome: "Willkommensnachricht", goodbye: "Abschiedsnachricht", antiSpam: "Anti-Spam", antiRaid: "Anti-Raid", floodLimit: "Nachrichtenlimit", floodWindow: "Fenster (Sekunden)", duplicateLimit: "Duplikatlimit", warningLimit: "Warnlimit", rules: "Gruppenregeln", save: "Einstellungen speichern", saved: "Gruppeneinstellungen gespeichert." };
const pl: GroupFormCopy = { empty: "Wybierz grupę do konfiguracji.", close: "Zamknij ustawienia grupy", description: "Szablony powitania i pożegnania obsługują lokalne daty, formatowanie Telegram i zmienne.", templateTitle: "Szablony i zmienne", formats: "Formaty: pogrubienie, kursywa, cytat, przekreślenie, spoiler, podkreślenie i kod.", formatsExample: markdown, variables: "Zmienne: wzmianka, nazwa i ID użytkownika, link, zasady i nazwa grupy, data i czas.", variablesExample: tokens, readOnly: "Możesz wyświetlić tę grupę, ale ustawienia może zmieniać tylko właściciel i administratorzy.", welcome: "Wiadomość powitalna", goodbye: "Wiadomość pożegnalna", antiSpam: "Antyspam", antiRaid: "Antynajazd", floodLimit: "Limit wiadomości", floodWindow: "Okno (sekundy)", duplicateLimit: "Limit duplikatów", warningLimit: "Limit ostrzeżeń", rules: "Zasady grupy", save: "Zapisz ustawienia", saved: "Ustawienia grupy zapisane." };
const vi: GroupFormCopy = { empty: "Chọn một nhóm để cấu hình.", close: "Đóng cài đặt nhóm", description: "Mẫu chào mừng và tạm biệt hỗ trợ ngày địa phương, định dạng Telegram và biến.", templateTitle: "Mẫu và biến", formats: "Định dạng: đậm, nghiêng, trích dẫn, gạch ngang, ẩn nội dung, gạch chân và mã.", formatsExample: markdown, variables: "Biến: đề cập, tên và ID người dùng, liên kết, quy tắc và tên nhóm, ngày và giờ.", variablesExample: tokens, readOnly: "Bạn có thể xem nhóm này, nhưng chỉ chủ sở hữu và quản trị viên mới có thể thay đổi cài đặt.", welcome: "Tin nhắn chào mừng", goodbye: "Tin nhắn tạm biệt", antiSpam: "Chống spam", antiRaid: "Chống raid", floodLimit: "Giới hạn tin nhắn", floodWindow: "Cửa sổ (giây)", duplicateLimit: "Giới hạn trùng lặp", warningLimit: "Giới hạn cảnh báo", rules: "Quy tắc nhóm", save: "Lưu cài đặt", saved: "Đã lưu cài đặt nhóm." };

export const dashboardGroupFormCopy: Record<DashboardLocale, GroupFormCopy> = { fa, en, ar, tr, ru, es, fr, pt, it, de, pl, vi };
