import type { DashboardLocale } from "./dashboardI18n";

export type DashboardCustomInvoiceCopy = {
  title: string;
  description: string;
  target: string;
  targetHint: string;
  channelId: string;
  amountStars: string;
  durationDays: string;
  expiryHours: string;
  send: string;
  invalid: string;
  sent: string;
  sentDetails: string;
  paymentNotice: string;
  sendFailed: string;
};

export const dashboardCustomInvoiceCopy: Record<DashboardLocale, DashboardCustomInvoiceCopy> = {
  fa: {
    title: "فاکتور سفارشی Stars", description: "فاکتور را مستقیماً برای مدیر کانال بفرستید؛ فعال‌سازی فقط پس از پرداخت تأییدشده انجام می‌شود.", target: "شناسه عددی یا نام کاربری گیرنده", targetHint: "گیرنده باید قبلاً ربات را در پیام خصوصی شروع کرده باشد.", channelId: "شناسه عددی کانال", amountStars: "مبلغ (Stars)", durationDays: "مدت فعال‌سازی (روز)", expiryHours: "مهلت پرداخت (ساعت)", send: "ارسال فاکتور Stars", invalid: "همهٔ مقادیر را به‌صورت معتبر وارد کنید.", sent: "فاکتور با موفقیت ارسال شد.", sentDetails: "کد پیگیری: {publicId}", paymentNotice: "پس از پرداخت موفق، کانال به‌صورت خودکار در عضویت اجباری فعال و نتیجه در ربات اعلام می‌شود.", sendFailed: "ارسال فاکتور ممکن نشد؛ دسترسی کانال و شروع گفت‌وگوی خصوصی گیرنده با ربات را بررسی کنید.",
  },
  en: {
    title: "Custom Stars invoice", description: "Send an invoice directly to the channel administrator. Activation happens only after Telegram confirms payment.", target: "Recipient ID or username", targetHint: "The recipient must have started the bot in a private chat.", channelId: "Numeric channel ID", amountStars: "Amount (Stars)", durationDays: "Activation period (days)", expiryHours: "Payment window (hours)", send: "Send Stars invoice", invalid: "Enter valid values in every field.", sent: "The invoice was sent.", sentDetails: "Reference: {publicId}", paymentNotice: "After successful payment, the channel is activated for forced join and the result is announced in the bot.", sendFailed: "The invoice could not be sent. Check channel access and that the recipient has started the bot privately.",
  },
  ar: {
    title: "فاتورة Stars مخصصة", description: "أرسل الفاتورة مباشرةً إلى مشرف القناة. لا يتم التفعيل إلا بعد تأكيد تيليجرام للدفع.", target: "معرّف المستلم أو اسم المستخدم", targetHint: "يجب أن يكون المستلم قد بدأ المحادثة الخاصة مع البوت.", channelId: "المعرّف الرقمي للقناة", amountStars: "المبلغ (Stars)", durationDays: "مدة التفعيل (أيام)", expiryHours: "مهلة الدفع (ساعات)", send: "إرسال فاتورة Stars", invalid: "أدخل قيماً صحيحة في كل الحقول.", sent: "تم إرسال الفاتورة.", sentDetails: "المرجع: {publicId}", paymentNotice: "بعد نجاح الدفع، تُفعَّل القناة تلقائياً للانضمام الإلزامي ويُعلن الناتج في البوت.", sendFailed: "تعذر إرسال الفاتورة. تحقق من صلاحية القناة ومن أن المستلم بدأ البوت في محادثة خاصة.",
  },
  tr: {
    title: "Özel Stars faturası", description: "Faturayı doğrudan kanal yöneticisine gönderin. Etkinleştirme yalnızca Telegram ödemeyi onayladığında yapılır.", target: "Alıcı kimliği veya kullanıcı adı", targetHint: "Alıcının botu özel sohbette başlatmış olması gerekir.", channelId: "Sayısal kanal kimliği", amountStars: "Tutar (Stars)", durationDays: "Etkinleştirme süresi (gün)", expiryHours: "Ödeme süresi (saat)", send: "Stars faturasını gönder", invalid: "Tüm alanlara geçerli değerler girin.", sent: "Fatura gönderildi.", sentDetails: "Referans: {publicId}", paymentNotice: "Başarılı ödemeden sonra kanal zorunlu katılım için otomatik etkinleştirilir ve sonuç botta bildirilir.", sendFailed: "Fatura gönderilemedi. Kanal erişimini ve alıcının botu özel olarak başlatmış olduğunu kontrol edin.",
  },
  ru: {
    title: "Пользовательский счёт Stars", description: "Отправьте счёт напрямую администратору канала. Активация происходит только после подтверждения оплаты Telegram.", target: "ID или имя пользователя получателя", targetHint: "Получатель должен предварительно запустить бота в личном чате.", channelId: "Числовой ID канала", amountStars: "Сумма (Stars)", durationDays: "Срок активации (дни)", expiryHours: "Окно оплаты (часы)", send: "Отправить счёт Stars", invalid: "Введите корректные значения во все поля.", sent: "Счёт отправлен.", sentDetails: "Код: {publicId}", paymentNotice: "После успешной оплаты канал автоматически активируется для обязательной подписки, а результат будет объявлен в боте.", sendFailed: "Не удалось отправить счёт. Проверьте доступ к каналу и то, что получатель запустил бота в личном чате.",
  },
  es: {
    title: "Factura personalizada de Stars", description: "Envía la factura directamente al administrador del canal. La activación solo ocurre después de que Telegram confirme el pago.", target: "ID o usuario del destinatario", targetHint: "El destinatario debe haber iniciado el bot en un chat privado.", channelId: "ID numérico del canal", amountStars: "Importe (Stars)", durationDays: "Periodo de activación (días)", expiryHours: "Ventana de pago (horas)", send: "Enviar factura de Stars", invalid: "Introduce valores válidos en todos los campos.", sent: "La factura se envió.", sentDetails: "Referencia: {publicId}", paymentNotice: "Tras un pago correcto, el canal se activa automáticamente para la suscripción obligatoria y el resultado se anuncia en el bot.", sendFailed: "No se pudo enviar la factura. Comprueba el acceso al canal y que el destinatario haya iniciado el bot de forma privada.",
  },
  fr: {
    title: "Facture Stars personnalisée", description: "Envoyez la facture directement à l’administrateur du canal. L’activation intervient uniquement après confirmation du paiement par Telegram.", target: "ID ou nom d’utilisateur du destinataire", targetHint: "Le destinataire doit avoir démarré le bot en conversation privée.", channelId: "ID numérique du canal", amountStars: "Montant (Stars)", durationDays: "Période d’activation (jours)", expiryHours: "Délai de paiement (heures)", send: "Envoyer la facture Stars", invalid: "Saisissez des valeurs valides dans tous les champs.", sent: "La facture a été envoyée.", sentDetails: "Référence : {publicId}", paymentNotice: "Après un paiement confirmé, le canal est automatiquement activé pour l’adhésion obligatoire et le résultat est annoncé dans le bot.", sendFailed: "La facture n’a pas pu être envoyée. Vérifiez l’accès au canal et que le destinataire a démarré le bot en privé.",
  },
  pt: {
    title: "Fatura Stars personalizada", description: "Envie a fatura diretamente ao administrador do canal. A ativação ocorre somente depois de o Telegram confirmar o pagamento.", target: "ID ou nome de utilizador do destinatário", targetHint: "O destinatário precisa ter iniciado o bot numa conversa privada.", channelId: "ID numérico do canal", amountStars: "Valor (Stars)", durationDays: "Período de ativação (dias)", expiryHours: "Prazo de pagamento (horas)", send: "Enviar fatura Stars", invalid: "Introduza valores válidos em todos os campos.", sent: "A fatura foi enviada.", sentDetails: "Referência: {publicId}", paymentNotice: "Após o pagamento confirmado, o canal é ativado automaticamente para a adesão obrigatória e o resultado é anunciado no bot.", sendFailed: "Não foi possível enviar a fatura. Verifique o acesso ao canal e se o destinatário iniciou o bot em privado.",
  },
  it: {
    title: "Fattura Stars personalizzata", description: "Invia la fattura direttamente all’amministratore del canale. L’attivazione avviene solo dopo la conferma del pagamento da parte di Telegram.", target: "ID o nome utente del destinatario", targetHint: "Il destinatario deve aver avviato il bot in una chat privata.", channelId: "ID numerico del canale", amountStars: "Importo (Stars)", durationDays: "Periodo di attivazione (giorni)", expiryHours: "Finestra di pagamento (ore)", send: "Invia fattura Stars", invalid: "Inserisci valori validi in tutti i campi.", sent: "La fattura è stata inviata.", sentDetails: "Riferimento: {publicId}", paymentNotice: "Dopo il pagamento riuscito, il canale viene attivato automaticamente per l’adesione obbligatoria e il risultato è annunciato nel bot.", sendFailed: "Non è stato possibile inviare la fattura. Verifica l’accesso al canale e che il destinatario abbia avviato il bot in privato.",
  },
  de: {
    title: "Individuelle Stars-Rechnung", description: "Senden Sie die Rechnung direkt an die Kanaladministration. Die Aktivierung erfolgt erst nach der Zahlungsbestätigung durch Telegram.", target: "Empfänger-ID oder Benutzername", targetHint: "Der Empfänger muss den Bot zuvor in einem privaten Chat gestartet haben.", channelId: "Numerische Kanal-ID", amountStars: "Betrag (Stars)", durationDays: "Aktivierungszeitraum (Tage)", expiryHours: "Zahlungsfenster (Stunden)", send: "Stars-Rechnung senden", invalid: "Geben Sie in allen Feldern gültige Werte ein.", sent: "Die Rechnung wurde gesendet.", sentDetails: "Referenz: {publicId}", paymentNotice: "Nach erfolgreicher Zahlung wird der Kanal automatisch für den Pflichtbeitritt aktiviert und das Ergebnis im Bot mitgeteilt.", sendFailed: "Die Rechnung konnte nicht gesendet werden. Prüfen Sie den Kanalzugriff und ob der Empfänger den Bot privat gestartet hat.",
  },
  pl: {
    title: "Niestandardowa faktura Stars", description: "Wyślij fakturę bezpośrednio do administratora kanału. Aktywacja następuje wyłącznie po potwierdzeniu płatności przez Telegram.", target: "ID lub nazwa użytkownika odbiorcy", targetHint: "Odbiorca musi wcześniej uruchomić bota w prywatnym czacie.", channelId: "Numeryczny ID kanału", amountStars: "Kwota (Stars)", durationDays: "Okres aktywacji (dni)", expiryHours: "Okno płatności (godziny)", send: "Wyślij fakturę Stars", invalid: "Wprowadź poprawne wartości we wszystkich polach.", sent: "Faktura została wysłana.", sentDetails: "Numer: {publicId}", paymentNotice: "Po udanej płatności kanał zostanie automatycznie aktywowany dla obowiązkowego dołączenia, a wynik ogłoszony w bocie.", sendFailed: "Nie można było wysłać faktury. Sprawdź dostęp do kanału i czy odbiorca uruchomił bota prywatnie.",
  },
  vi: {
    title: "Hoá đơn Stars tuỳ chỉnh", description: "Gửi hoá đơn trực tiếp cho quản trị viên kênh. Việc kích hoạt chỉ diễn ra sau khi Telegram xác nhận thanh toán.", target: "ID hoặc tên người dùng của người nhận", targetHint: "Người nhận phải đã khởi động bot trong cuộc trò chuyện riêng tư.", channelId: "ID kênh dạng số", amountStars: "Số tiền (Stars)", durationDays: "Thời hạn kích hoạt (ngày)", expiryHours: "Thời hạn thanh toán (giờ)", send: "Gửi hoá đơn Stars", invalid: "Hãy nhập giá trị hợp lệ vào mọi trường.", sent: "Hoá đơn đã được gửi.", sentDetails: "Mã tham chiếu: {publicId}", paymentNotice: "Sau khi thanh toán thành công, kênh được kích hoạt tự động cho tham gia bắt buộc và kết quả được thông báo trong bot.", sendFailed: "Không thể gửi hoá đơn. Hãy kiểm tra quyền truy cập kênh và việc người nhận đã khởi động bot riêng tư.",
  },
};


export const dashboardCustomInvoiceActions: Record<DashboardLocale, { channelReference: string; targetReference: string; targetId: string; channelId: string; resolve: string; resolved: string; resolveFailed: string }> = {
  fa: { channelReference: "لینک یا یوزرنیم کانال", targetReference: "لینک، یوزرنیم یا شناسهٔ کاربر", targetId: "شناسهٔ عددی گیرنده", channelId: "شناسهٔ عددی کانال", resolve: "تبدیل", resolved: "شناسه با موفقیت شناسایی شد", resolveFailed: "مرجع پیدا نشد؛ لینک، یوزرنیم یا دسترسی را بررسی کنید." },
  en: { channelReference: "Channel link or username", targetReference: "User link, username, or ID", targetId: "Recipient numeric ID", channelId: "Channel numeric ID", resolve: "Generate / Resolve", resolved: "ID resolved successfully", resolveFailed: "Reference not found. Check the link, username, or access." },
  ar: { channelReference: "رابط القناة أو اسم المستخدم", targetReference: "رابط المستخدم أو اسمه أو معرّفه", targetId: "المعرّف الرقمي للمستلم", channelId: "المعرّف الرقمي للقناة", resolve: "توليد / تحويل", resolved: "تم التعرّف على المعرّف بنجاح", resolveFailed: "لم يتم العثور على المرجع. تحقق من الرابط أو الاسم أو الصلاحية." },
  tr: { channelReference: "Kanal bağlantısı veya kullanıcı adı", targetReference: "Kullanıcı bağlantısı, adı veya kimliği", targetId: "Alıcının sayısal kimliği", channelId: "Kanal sayısal kimliği", resolve: "Oluştur / Çözümle", resolved: "Kimlik başarıyla çözüldü", resolveFailed: "Referans bulunamadı. Bağlantıyı, adı veya erişimi kontrol edin." },
  ru: { channelReference: "Ссылка или имя канала", targetReference: "Ссылка, имя или ID пользователя", targetId: "Числовой ID получателя", channelId: "Числовой ID канала", resolve: "Создать / определить", resolved: "ID успешно определён", resolveFailed: "Ссылка не найдена. Проверьте ссылку, имя или доступ." },
  es: { channelReference: "Enlace o usuario del canal", targetReference: "Enlace, usuario o ID del destinatario", targetId: "ID numérico del destinatario", channelId: "ID numérico del canal", resolve: "Generar / resolver", resolved: "ID identificado correctamente", resolveFailed: "No se encontró la referencia. Comprueba el enlace, usuario o acceso." },
  fr: { channelReference: "Lien ou nom d’utilisateur du canal", targetReference: "Lien, nom ou ID du destinataire", targetId: "ID numérique du destinataire", channelId: "ID numérique du canal", resolve: "Générer / résoudre", resolved: "ID identifié avec succès", resolveFailed: "Référence introuvable. Vérifiez le lien, le nom ou l’accès." },
  pt: { channelReference: "Link ou nome de utilizador do canal", targetReference: "Link, nome ou ID do destinatário", targetId: "ID numérico do destinatário", channelId: "ID numérico do canal", resolve: "Gerar / resolver", resolved: "ID identificado com sucesso", resolveFailed: "Referência não encontrada. Verifique o link, nome ou acesso." },
  it: { channelReference: "Link o nome utente del canale", targetReference: "Link, nome utente o ID del destinatario", targetId: "ID numerico del destinatario", channelId: "ID numerico del canale", resolve: "Genera / risolvi", resolved: "ID identificato correttamente", resolveFailed: "Riferimento non trovato. Controlla link, nome utente o accesso." },
  de: { channelReference: "Kanal-Link oder Benutzername", targetReference: "Link, Benutzername oder ID des Empfängers", targetId: "Numerische Empfänger-ID", channelId: "Numerische Kanal-ID", resolve: "Erstellen / auflösen", resolved: "ID erfolgreich ermittelt", resolveFailed: "Referenz nicht gefunden. Prüfen Sie Link, Benutzername oder Zugriff." },
  pl: { channelReference: "Link lub nazwa użytkownika kanału", targetReference: "Link, nazwa lub ID odbiorcy", targetId: "Numeryczny ID odbiorcy", channelId: "Numeryczny ID kanału", resolve: "Generuj / rozpoznaj", resolved: "ID rozpoznano pomyślnie", resolveFailed: "Nie znaleziono odnośnika. Sprawdź link, nazwę lub dostęp." },
  vi: { channelReference: "Liên kết hoặc tên kênh", targetReference: "Liên kết, tên hoặc ID người nhận", targetId: "ID số của người nhận", channelId: "ID số của kênh", resolve: "Tạo / phân giải", resolved: "Đã nhận diện ID thành công", resolveFailed: "Không tìm thấy tham chiếu. Hãy kiểm tra liên kết, tên hoặc quyền truy cập." },
};
