import type { DashboardLocale } from "./dashboardI18n";

export type DashboardRuntimeCopy = {
  about: string;
  history: string;
  loadingData: string;
  loadingWait: string;
  adminTelegram: string;
  statusLabels: Record<string, string>;
  errors: {
    generic: string;
    permission: string;
    network: string;
    service: string;
    invalid: string;
  };
};

const runtimeCopy: Record<DashboardLocale, DashboardRuntimeCopy> = {
  fa: { about: "دربارهٔ ما", history: "تاریخچهٔ کارت‌ها", loadingData: "در حال دریافت اطلاعات", loadingWait: "لطفاً کمی صبر کنید…", adminTelegram: "مدیر تلگرام", statusLabels: { active: "فعال", paid: "پرداخت‌شده", sent: "ارسال‌شده", completed: "تکمیل‌شده", pending_approval: "در انتظار تأیید", pending: "در انتظار", awaiting_payment: "در انتظار پرداخت", warning: "هشدار", failed: "ناموفق", rejected: "ردشده", expired: "منقضی‌شده", critical: "بحرانی", permission_lost: "دسترسی از دست رفته" }, errors: { generic: "درخواست انجام نشد. لطفاً چند لحظه بعد دوباره تلاش کنید.", permission: "دسترسی لازم برای این بخش وجود ندارد.", network: "ارتباط با Kronos Guard برقرار نشد. اتصال اینترنت را بررسی و دوباره تلاش کنید.", service: "سرویس موقتاً در دسترس نیست. لطفاً چند لحظه بعد دوباره تلاش کنید.", invalid: "اطلاعات واردشده کامل یا معتبر نیست." } },
  en: { about: "About us", history: "Card history", loadingData: "Loading data", loadingWait: "Please wait…", adminTelegram: "Telegram admin", statusLabels: { active: "Active", paid: "Paid", sent: "Sent", completed: "Completed", pending_approval: "Pending approval", pending: "Pending", awaiting_payment: "Awaiting payment", warning: "Warning", failed: "Failed", rejected: "Rejected", expired: "Expired", critical: "Critical", permission_lost: "Permission lost" }, errors: { generic: "The request could not be completed. Please try again shortly.", permission: "You do not have permission to access this section.", network: "Kronos Guard could not connect. Check your internet connection and try again.", service: "The service is temporarily unavailable. Please try again shortly.", invalid: "The submitted information is incomplete or invalid." } },
  ar: { about: "معلومات عنا", history: "سجل البطاقات", loadingData: "جارٍ تحميل البيانات", loadingWait: "يرجى الانتظار…", adminTelegram: "مشرف تيليجرام", statusLabels: { active: "نشط", paid: "مدفوع", sent: "مُرسل", completed: "مكتمل", pending_approval: "بانتظار الموافقة", pending: "قيد الانتظار", awaiting_payment: "بانتظار الدفع", warning: "تحذير", failed: "فشل", rejected: "مرفوض", expired: "منتهي", critical: "حرج", permission_lost: "فُقد الإذن" }, errors: { generic: "تعذر إكمال الطلب. يرجى المحاولة مرة أخرى بعد قليل.", permission: "لا تملك صلاحية الوصول إلى هذا القسم.", network: "تعذر الاتصال بـ Kronos Guard. تحقق من اتصال الإنترنت وحاول مرة أخرى.", service: "الخدمة غير متاحة مؤقتًا. يرجى المحاولة بعد قليل.", invalid: "المعلومات المُدخلة غير مكتملة أو غير صالحة." } },
  tr: { about: "Hakkımızda", history: "Kart geçmişi", loadingData: "Veriler yükleniyor", loadingWait: "Lütfen bekleyin…", adminTelegram: "Telegram yöneticisi", statusLabels: { active: "Etkin", paid: "Ödendi", sent: "Gönderildi", completed: "Tamamlandı", pending_approval: "Onay bekliyor", pending: "Bekliyor", awaiting_payment: "Ödeme bekliyor", warning: "Uyarı", failed: "Başarısız", rejected: "Reddedildi", expired: "Süresi doldu", critical: "Kritik", permission_lost: "İzin kaybedildi" }, errors: { generic: "İstek tamamlanamadı. Lütfen kısa süre sonra tekrar deneyin.", permission: "Bu bölüme erişim izniniz yok.", network: "Kronos Guard bağlantı kuramadı. İnternet bağlantınızı kontrol edip tekrar deneyin.", service: "Hizmet geçici olarak kullanılamıyor. Lütfen kısa süre sonra tekrar deneyin.", invalid: "Girilen bilgiler eksik veya geçersiz." } },
  ru: { about: "О нас", history: "История карточек", loadingData: "Загрузка данных", loadingWait: "Пожалуйста, подождите…", adminTelegram: "Администратор Telegram", statusLabels: { active: "Активен", paid: "Оплачен", sent: "Отправлен", completed: "Завершён", pending_approval: "Ожидает подтверждения", pending: "Ожидает", awaiting_payment: "Ожидает оплаты", warning: "Предупреждение", failed: "Ошибка", rejected: "Отклонён", expired: "Истёк", critical: "Критический", permission_lost: "Доступ потерян" }, errors: { generic: "Не удалось выполнить запрос. Повторите попытку позже.", permission: "У вас нет доступа к этому разделу.", network: "Не удалось подключиться к Kronos Guard. Проверьте интернет и повторите попытку.", service: "Сервис временно недоступен. Повторите попытку позже.", invalid: "Введённые данные неполны или недействительны." } },
  es: { about: "Sobre nosotros", history: "Historial de tarjetas", loadingData: "Cargando datos", loadingWait: "Espera un momento…", adminTelegram: "Administrador de Telegram", statusLabels: { active: "Activo", paid: "Pagado", sent: "Enviado", completed: "Completado", pending_approval: "Pendiente de aprobación", pending: "Pendiente", awaiting_payment: "Pendiente de pago", warning: "Advertencia", failed: "Fallido", rejected: "Rechazado", expired: "Caducado", critical: "Crítico", permission_lost: "Permiso perdido" }, errors: { generic: "No se pudo completar la solicitud. Inténtalo de nuevo en unos instantes.", permission: "No tienes permiso para acceder a esta sección.", network: "Kronos Guard no pudo conectarse. Comprueba tu conexión a Internet e inténtalo de nuevo.", service: "El servicio no está disponible temporalmente. Inténtalo de nuevo en unos instantes.", invalid: "La información introducida está incompleta o no es válida." } },
  fr: { about: "À propos de nous", history: "Historique des cartes", loadingData: "Chargement des données", loadingWait: "Veuillez patienter…", adminTelegram: "Administrateur Telegram", statusLabels: { active: "Actif", paid: "Payé", sent: "Envoyé", completed: "Terminé", pending_approval: "En attente d’approbation", pending: "En attente", awaiting_payment: "En attente de paiement", warning: "Avertissement", failed: "Échec", rejected: "Refusé", expired: "Expiré", critical: "Critique", permission_lost: "Autorisation perdue" }, errors: { generic: "La requête n’a pas pu être terminée. Réessayez dans un instant.", permission: "Vous n’avez pas l’autorisation d’accéder à cette section.", network: "Kronos Guard n’a pas pu se connecter. Vérifiez votre connexion Internet et réessayez.", service: "Le service est temporairement indisponible. Réessayez dans un instant.", invalid: "Les informations saisies sont incomplètes ou invalides." } },
  pt: { about: "Sobre nós", history: "Histórico de cartões", loadingData: "Carregando dados", loadingWait: "Aguarde um momento…", adminTelegram: "Administrador do Telegram", statusLabels: { active: "Ativo", paid: "Pago", sent: "Enviado", completed: "Concluído", pending_approval: "Aguardando aprovação", pending: "Pendente", awaiting_payment: "Aguardando pagamento", warning: "Aviso", failed: "Falhou", rejected: "Rejeitado", expired: "Expirado", critical: "Crítico", permission_lost: "Permissão perdida" }, errors: { generic: "Não foi possível concluir a solicitação. Tente novamente em instantes.", permission: "Você não tem permissão para acessar esta seção.", network: "O Kronos Guard não conseguiu conectar. Verifique sua internet e tente novamente.", service: "O serviço está temporariamente indisponível. Tente novamente em instantes.", invalid: "As informações inseridas estão incompletas ou inválidas." } },
  it: { about: "Chi siamo", history: "Cronologia delle schede", loadingData: "Caricamento dati", loadingWait: "Attendi…", adminTelegram: "Amministratore Telegram", statusLabels: { active: "Attivo", paid: "Pagato", sent: "Inviato", completed: "Completato", pending_approval: "In attesa di approvazione", pending: "In attesa", awaiting_payment: "In attesa di pagamento", warning: "Avviso", failed: "Non riuscito", rejected: "Rifiutato", expired: "Scaduto", critical: "Critico", permission_lost: "Permesso perso" }, errors: { generic: "Impossibile completare la richiesta. Riprova tra poco.", permission: "Non hai il permesso di accedere a questa sezione.", network: "Kronos Guard non è riuscito a connettersi. Controlla la connessione e riprova.", service: "Il servizio è temporaneamente non disponibile. Riprova tra poco.", invalid: "Le informazioni inserite sono incomplete o non valide." } },
  de: { about: "Über uns", history: "Statuskarten-Verlauf", loadingData: "Daten werden geladen", loadingWait: "Bitte warten…", adminTelegram: "Telegram-Administrator", statusLabels: { active: "Aktiv", paid: "Bezahlt", sent: "Gesendet", completed: "Abgeschlossen", pending_approval: "Genehmigung ausstehend", pending: "Ausstehend", awaiting_payment: "Zahlung ausstehend", warning: "Warnung", failed: "Fehlgeschlagen", rejected: "Abgelehnt", expired: "Abgelaufen", critical: "Kritisch", permission_lost: "Berechtigung verloren" }, errors: { generic: "Die Anfrage konnte nicht abgeschlossen werden. Bitte versuche es gleich noch einmal.", permission: "Du hast keine Berechtigung für diesen Bereich.", network: "Kronos Guard konnte keine Verbindung herstellen. Prüfe deine Internetverbindung und versuche es erneut.", service: "Der Dienst ist vorübergehend nicht verfügbar. Bitte versuche es gleich noch einmal.", invalid: "Die eingegebenen Informationen sind unvollständig oder ungültig." } },
  pl: { about: "O nas", history: "Historia kart", loadingData: "Ładowanie danych", loadingWait: "Proszę czekać…", adminTelegram: "Administrator Telegrama", statusLabels: { active: "Aktywne", paid: "Opłacone", sent: "Wysłane", completed: "Ukończone", pending_approval: "Oczekuje na zatwierdzenie", pending: "Oczekujące", awaiting_payment: "Oczekuje na płatność", warning: "Ostrzeżenie", failed: "Nieudane", rejected: "Odrzucone", expired: "Wygasłe", critical: "Krytyczne", permission_lost: "Utracono uprawnienia" }, errors: { generic: "Nie udało się wykonać żądania. Spróbuj ponownie za chwilę.", permission: "Nie masz uprawnień do tej sekcji.", network: "Kronos Guard nie może się połączyć. Sprawdź internet i spróbuj ponownie.", service: "Usługa jest tymczasowo niedostępna. Spróbuj ponownie za chwilę.", invalid: "Wprowadzone informacje są niepełne lub nieprawidłowe." } },
  vi: { about: "Về chúng tôi", history: "Lịch sử thẻ", loadingData: "Đang tải dữ liệu", loadingWait: "Vui lòng chờ…", adminTelegram: "Quản trị viên Telegram", statusLabels: { active: "Đang hoạt động", paid: "Đã thanh toán", sent: "Đã gửi", completed: "Đã hoàn tất", pending_approval: "Chờ phê duyệt", pending: "Đang chờ", awaiting_payment: "Chờ thanh toán", warning: "Cảnh báo", failed: "Thất bại", rejected: "Bị từ chối", expired: "Đã hết hạn", critical: "Nghiêm trọng", permission_lost: "Mất quyền truy cập" }, errors: { generic: "Không thể hoàn tất yêu cầu. Vui lòng thử lại sau ít phút.", permission: "Bạn không có quyền truy cập phần này.", network: "Kronos Guard không thể kết nối. Hãy kiểm tra Internet và thử lại.", service: "Dịch vụ tạm thời không khả dụng. Vui lòng thử lại sau ít phút.", invalid: "Thông tin đã nhập chưa đầy đủ hoặc không hợp lệ." } },
};

export function dashboardRuntimeCopy(locale: DashboardLocale): DashboardRuntimeCopy {
  return runtimeCopy[locale];
}

export function dashboardRuntimeCopyFor(locale: DashboardLocale | null | undefined): DashboardRuntimeCopy {
  return runtimeCopy[locale && locale in runtimeCopy ? locale : "fa"];
}

export const dashboardRuntimeLocales = Object.keys(runtimeCopy) as DashboardLocale[];
