export const supportedLocales = ["fa", "en", "ar", "tr", "ru", "es", "fr", "pt", "it", "de", "pl", "vi"] as const;
export type SupportedLocale = typeof supportedLocales[number];

type BaseMessageKey = "welcome" | "languageUpdated" | "languageHelp" | "languageSelector" | "forcedJoinLocked" | "forcedJoinStillMissing" | "forcedJoinVerificationUnavailable" | "membershipVerified";
type ControlMessageKey = "joinChannel" | "verifyMembership";
export type MessageKey = BaseMessageKey | ControlMessageKey;

const messages: Record<SupportedLocale, Record<MessageKey, string>> = {
  fa: { welcome: "<b>به 𝐾𝑟𝑜𝑛𝑜𝑠 𝐺𝑢𝑎𝑟𝑑 خوش آمدی</b>\n<i>کنترل سنتر امنیت و مدیریت حرفهای گروه</i>\n\n<b>راه‌اندازی سریع</b>\n• ربات را به گروه اضافه کن.\n• دسترسی مدیر ربات را فعال کن.\n• تنظیمات هر گروه را از «پنل مدیریت» کنترل کن.\n\n<b>دسترسی‌های مهم</b>\n• راهنمای فرمان‌ها: /help\n• انتخاب زبان: دکمهٔ «زبان»\n• کنترل گروه‌ها: «پنل مدیریت»\n\n<blockquote>«مدیریت حرفه‌ای فقط واکنش به مشکل نیست؛ پیشگیری هوشمندانه از آن است.» — Kronos Guard</blockquote>", languageUpdated: "زبان ربات با موفقیت به فارسی تغییر کرد.", languageHelp: "برای انتخاب زبان، دکمه «زبان» را بزنید.", languageSelector: "زبان دلخواه خود را انتخاب کنید:", forcedJoinLocked: "شما هنوز به همهٔ مقصدهای اجباری نپیوسته‌اید.", forcedJoinStillMissing: "عضویت شما در این مقصدها هنوز تأیید نشده است:", forcedJoinVerificationUnavailable: "بررسی عضویت فعلاً ممکن نیست؛ لطفاً چند لحظهٔ دیگر دوباره تلاش کنید.", membershipVerified: "عضویت شما تأیید شد؛ دسترسی باز است.", joinChannel: "عضویت در کانال 🔗", verifyMembership: "عضو شدم" },
  en: { welcome: "Welcome to Kronos Guard. Add the bot as a group administrator to manage your community.", languageUpdated: "Your bot language has been changed to English.", languageHelp: "Use the Language button to choose your language.", languageSelector: "Choose your preferred language:", forcedJoinLocked: "You have not joined all required destinations yet.", forcedJoinStillMissing: "Membership is still missing in these destinations:", forcedJoinVerificationUnavailable: "Membership verification is temporarily unavailable. Please try again shortly.", membershipVerified: "Your membership is verified; access is now unlocked.", joinChannel: "Join Channel 🔗", verifyMembership: "I've joined" },
  ar: { welcome: "مرحباً بك في Kronos Guard. أضف الروبوت مشرفاً لإدارة مجموعتك.", languageUpdated: "تم تغيير لغة الروبوت إلى العربية.", languageHelp: "استخدم زر اللغة لاختيار لغتك.", languageSelector: "اختر لغتك المفضلة:", forcedJoinLocked: "لم تنضم إلى جميع الوجهات المطلوبة بعد.", forcedJoinStillMissing: "لم يتم تأكيد عضويتك في الوجهات التالية:", forcedJoinVerificationUnavailable: "يتعذر التحقق من العضوية مؤقتاً. حاول مرة أخرى بعد قليل.", membershipVerified: "تم التحقق من العضوية وفتح الوصول.", joinChannel: "الانضمام إلى القناة 🔗", verifyMembership: "لقد انضممت" },
  tr: { welcome: "Kronos Guard'a hoş geldiniz. Topluluğunuzu yönetmek için botu yönetici yapın.", languageUpdated: "Bot dili Türkçe olarak değiştirildi.", languageHelp: "Dil seçmek için Dil düğmesini kullanın.", languageSelector: "Tercih ettiğiniz dili seçin:", forcedJoinLocked: "Henüz tüm zorunlu hedeflere katılmadınız.", forcedJoinStillMissing: "Üyeliğiniz şu hedeflerde hâlâ eksik:", forcedJoinVerificationUnavailable: "Üyelik doğrulaması geçici olarak kullanılamıyor. Lütfen kısa süre sonra tekrar deneyin.", membershipVerified: "Üyeliğiniz doğrulandı; erişim açıldı.", joinChannel: "Kanala katıl 🔗", verifyMembership: "Katıldım" },
  ru: { welcome: "Добро пожаловать в Kronos Guard. Сделайте бота администратором группы.", languageUpdated: "Язык бота изменён на русский.", languageHelp: "Используйте кнопку языка, чтобы выбрать язык.", languageSelector: "Выберите предпочитаемый язык:", forcedJoinLocked: "Вы ещё не вступили во все обязательные цели.", forcedJoinStillMissing: "Членство всё ещё отсутствует в следующих целях:", forcedJoinVerificationUnavailable: "Проверка членства временно недоступна. Повторите попытку позже.", membershipVerified: "Членство подтверждено, доступ открыт.", joinChannel: "Подписаться на канал 🔗", verifyMembership: "Я вступил" },
  es: { welcome: "Bienvenido a Kronos Guard. Añade el bot como administrador del grupo.", languageUpdated: "El idioma del bot se cambió a español.", languageHelp: "Usa el botón Idioma para elegir tu idioma.", languageSelector: "Elige tu idioma preferido:", forcedJoinLocked: "Aún no te has unido a todos los destinos obligatorios.", forcedJoinStillMissing: "Tu membresía aún falta en estos destinos:", forcedJoinVerificationUnavailable: "La verificación de membresía no está disponible temporalmente. Inténtalo de nuevo pronto.", membershipVerified: "Tu membresía fue verificada; el acceso está desbloqueado.", joinChannel: "Unirse al canal 🔗", verifyMembership: "Ya me uní" },
  fr: { welcome: "Bienvenue sur Kronos Guard. Ajoutez le bot comme administrateur du groupe.", languageUpdated: "La langue du bot a été changée en français.", languageHelp: "Utilisez le bouton Langue pour choisir votre langue.", languageSelector: "Choisissez votre langue préférée :", forcedJoinLocked: "Vous n'avez pas encore rejoint toutes les destinations requises.", forcedJoinStillMissing: "Votre adhésion manque encore dans ces destinations :", forcedJoinVerificationUnavailable: "La vérification de l'adhésion est temporairement indisponible. Réessayez bientôt.", membershipVerified: "Votre adhésion est vérifiée ; l'accès est débloqué.", joinChannel: "Rejoindre le canal 🔗", verifyMembership: "J'ai rejoint" },
  pt: { welcome: "Bem-vindo ao Kronos Guard. Adicione o bot como administrador do grupo.", languageUpdated: "O idioma do bot foi alterado para português.", languageHelp: "Use o botão Idioma para escolher o seu idioma.", languageSelector: "Escolha o seu idioma preferido:", forcedJoinLocked: "Você ainda não entrou em todos os destinos obrigatórios.", forcedJoinStillMissing: "Sua participação ainda falta nestes destinos:", forcedJoinVerificationUnavailable: "A verificação está temporariamente indisponível. Tente novamente em instantes.", membershipVerified: "Sua associação foi verificada; o acesso está liberado.", joinChannel: "Entrar no canal 🔗", verifyMembership: "Entrei" },
  it: { welcome: "Benvenuto in Kronos Guard. Aggiungi il bot come amministratore del gruppo.", languageUpdated: "La lingua del bot è stata cambiata in italiano.", languageHelp: "Usa il pulsante Lingua per scegliere la tua lingua.", languageSelector: "Scegli la tua lingua preferita:", forcedJoinLocked: "Non hai ancora aderito a tutte le destinazioni richieste.", forcedJoinStillMissing: "La tua iscrizione manca ancora in queste destinazioni:", forcedJoinVerificationUnavailable: "La verifica dell'iscrizione è temporaneamente non disponibile. Riprova tra poco.", membershipVerified: "L'iscrizione è verificata; l'accesso è sbloccato.", joinChannel: "Unisciti al canale 🔗", verifyMembership: "Ho aderito" },
  de: { welcome: "Willkommen bei Kronos Guard. Füge den Bot als Gruppenadministrator hinzu.", languageUpdated: "Die Botsprache wurde auf Deutsch geändert.", languageHelp: "Verwende die Sprachschaltfläche, um deine Sprache zu wählen.", languageSelector: "Wähle deine bevorzugte Sprache:", forcedJoinLocked: "Du bist noch nicht allen Pflichtzielen beigetreten.", forcedJoinStillMissing: "Deine Mitgliedschaft fehlt noch bei diesen Zielen:", forcedJoinVerificationUnavailable: "Die Mitgliedschaft kann vorübergehend nicht geprüft werden. Versuche es gleich erneut.", membershipVerified: "Deine Mitgliedschaft wurde bestätigt; der Zugang ist entsperrt.", joinChannel: "Kanal beitreten 🔗", verifyMembership: "Ich bin beigetreten" },
  pl: { welcome: "Witamy w Kronos Guard. Dodaj bota jako administratora grupy.", languageUpdated: "Język bota został zmieniony na polski.", languageHelp: "Użyj przycisku Język, aby wybrać język.", languageSelector: "Wybierz preferowany język:", forcedJoinLocked: "Nie dołączyłeś jeszcze do wszystkich wymaganych miejsc.", forcedJoinStillMissing: "Członkostwa nadal brakuje w tych miejscach:", forcedJoinVerificationUnavailable: "Weryfikacja członkostwa jest chwilowo niedostępna. Spróbuj ponownie za chwilę.", membershipVerified: "Członkostwo zostało potwierdzone; dostęp jest odblokowany.", joinChannel: "Dołącz do kanału 🔗", verifyMembership: "Dołączyłem(-am)" },
  vi: { welcome: "Chào mừng đến với Kronos Guard. Hãy thêm bot làm quản trị viên nhóm.", languageUpdated: "Ngôn ngữ bot đã được đổi sang tiếng Việt.", languageHelp: "Dùng nút Ngôn ngữ để chọn ngôn ngữ của bạn.", languageSelector: "Chọn ngôn ngữ bạn muốn:", forcedJoinLocked: "Bạn chưa tham gia tất cả các điểm bắt buộc.", forcedJoinStillMissing: "Bạn vẫn chưa tham gia các điểm sau:", forcedJoinVerificationUnavailable: "Tạm thời không thể xác minh thành viên. Vui lòng thử lại sau.", membershipVerified: "Tư cách thành viên đã được xác minh; quyền truy cập đã mở.", joinChannel: "Tham gia kênh 🔗", verifyMembership: "Tôi đã tham gia" },
};

export function normalizeLocale(value: string | null | undefined): SupportedLocale {
  const base = value?.toLocaleLowerCase("en-US").split(/[-_]/)[0];
  return supportedLocales.includes(base as SupportedLocale) ? base as SupportedLocale : "fa";
}

export function translate(locale: string | null | undefined, key: MessageKey): string {
  const localized = messages[normalizeLocale(locale)][key];
  if (localized) return localized;
  return messages.fa[key];
}
