import React, { useState } from "react";
import { RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import type { DashboardLocale } from "@/lib/dashboardI18n";
import { trpc } from "@/lib/trpc";
import { NobitexUsdtBoard, type NobitexRange, type NobitexUsdtMarket } from "@/components/NobitexUsdtBoard";

type NobitexMarketQuote = { id: string; symbol: string; market: string; latestToman: number; bestBuyToman: number; bestSellToman: number; dayChangePercent: number; volumeToman: number | null };
type NobitexMarketsPayload = { source: "nobitex"; updatedAt: string; isStale: boolean; markets: NobitexMarketQuote[] };

function toman(value: number) { return `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 0, notation: value >= 1_000_000_000 ? "compact" : "standard" }).format(value)} تومان`; }
function marketTime(value: string, locale: DashboardLocale) { return new Intl.DateTimeFormat(locale === "fa" ? "fa-IR-u-nu-latn" : "en-US", { timeZone: "Asia/Tehran", hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(value)); }

export function NobitexMarketSection({ locale }: { locale: DashboardLocale }) {
  const [range, setRange] = useState<NobitexRange>("1d");
  const market = trpc.dashboard.cryptoMarket.nobitexUsdt.useQuery({ range }, { refetchInterval: 30_000, refetchIntervalInBackground: false });
  const marketList = trpc.dashboard.cryptoMarket.nobitexMarkets.useQuery({ limit: 30 }, { refetchInterval: 30_000, refetchIntervalInBackground: false });
  const fa = locale === "fa";
  const labels = fa ? { title: "بازارهای ریالی نوبیتکس", subtitle: "قیمت، بهترین خرید و فروش و تغییرات واقعی هر بازار", last: "آخرین", buy: "خرید", sell: "فروش", update: "دریافت در تهران", refresh: "تازه‌سازی فهرست" } : { title: "Nobitex rial markets", subtitle: "Live last, best bid/ask, and daily movement", last: "Last", buy: "Bid", sell: "Ask", update: "Received in Tehran", refresh: "Refresh list" };
  const data = marketList.data as NobitexMarketsPayload | undefined;
  return <div className="space-y-5"><NobitexUsdtBoard market={market.data as NobitexUsdtMarket | undefined} isLoading={market.isLoading} isFetching={market.isFetching} hasError={Boolean(market.error)} range={range} onRangeChange={setRange} onRefresh={() => void market.refetch()} locale={locale} /><Card className="kronos-card overflow-hidden border-cyan-300/15 bg-slate-950/35"><CardContent className="p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-white">{labels.title}</h3><p className="mt-1 text-xs text-slate-500">{labels.subtitle}</p></div><Button type="button" size="icon" variant="outline" aria-label={labels.refresh} onClick={() => void marketList.refetch()} disabled={marketList.isFetching} className="border-white/10 bg-white/[.035] text-cyan-100 hover:bg-white/10"><RefreshCw className={`h-4 w-4 ${marketList.isFetching ? "animate-spin" : ""}`} /></Button></div>{marketList.isLoading ? <div className="mt-4 space-y-2">{Array.from({ length: 6 }).map((_, index) => <Skeleton key={index} className="h-16 rounded-xl bg-white/5" />)}</div> : null}{data?.markets?.length ? <div className="mt-4 max-h-[52vh] overflow-y-auto rounded-2xl border border-white/8 bg-slate-950/25" role="list" aria-label={labels.title}>{data.markets.map(quote => <div key={quote.id} role="listitem" className="grid grid-cols-[1.2fr_1fr] gap-3 border-b border-white/8 px-3 py-3 last:border-b-0 sm:grid-cols-[1.2fr_1fr_1fr_1fr]"><div className="min-w-0"><p dir="ltr" className="font-black text-white">{quote.symbol}</p><p dir="ltr" className="mt-1 text-[10px] font-bold tracking-[.12em] text-slate-500">{quote.market}</p></div><div><p className="text-[10px] text-slate-500">{labels.last}</p><p dir="ltr" className="mt-1 text-xs font-black text-cyan-100">{toman(quote.latestToman)}</p></div><div className="hidden sm:block"><p className="text-[10px] text-slate-500">{labels.buy} / {labels.sell}</p><p dir="ltr" className="mt-1 text-xs font-bold text-slate-200">{toman(quote.bestBuyToman)} / {toman(quote.bestSellToman)}</p></div><div className="text-left"><p dir="ltr" className={`mt-2 text-xs font-black ${quote.dayChangePercent >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{quote.dayChangePercent >= 0 ? "+" : ""}{quote.dayChangePercent.toFixed(2)}%</p></div></div>)}</div> : null}{marketList.error ? <p role="status" className="mt-4 rounded-xl border border-amber-300/15 bg-amber-300/[.05] p-3 text-xs text-amber-100">{fa ? "فهرست نوبیتکس موقتاً در دسترس نیست؛ برای نمایش نرخ ثابت از دادهٔ قدیمی استفاده نمی‌شود." : "Nobitex list is temporarily unavailable; no fixed stale quote is shown."}</p> : null}{data ? <p className="mt-3 text-left text-[10px] text-slate-500">{labels.update}: <span dir="ltr">{marketTime(data.updatedAt, locale)}</span>{data.isStale ? " · cached" : ""}</p> : null}</CardContent></Card></div>;
}
